"use client";

import { useOrganizationContext } from "@saas/organizations/hooks/use-organization-context";
import { orpcClient } from "@shared/lib/orpc-client";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from "@ui/components/alert-dialog";
import { Badge } from "@ui/components/badge";
import { Button } from "@ui/components/button";
import { Card } from "@ui/components/card";
import { Input } from "@ui/components/input";
import { Textarea } from "@ui/components/textarea";
import {
	Tooltip,
	TooltipContent,
	TooltipTrigger,
} from "@ui/components/tooltip";
import { cn } from "@ui/lib";
import {
	AlertCircleIcon,
	BookmarkPlusIcon,
	CheckCircleIcon,
	ChevronDownIcon,
	ChevronUpIcon,
	ClockIcon,
	GitBranchIcon,
	Loader2Icon,
	PencilIcon,
	PlayIcon,
	PlusIcon,
	RefreshCwIcon,
	Trash2Icon,
	XCircleIcon,
} from "lucide-react";
import { useTranslations } from "next-intl";
import type React from "react";
import { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { useKanbanRuntimeDetected } from "../../projects/hooks/use-kanban-status";
import {
	getExecutionProviderLabel,
	getExecutionProviderPlatformLabel,
} from "../../projects/lib/implementation-session-labels";

interface WeavePlanStep {
	id: string;
	text: string;
	agent: string;
	status?: string;
}

interface WeavePlan {
	id: string;
	name: string;
	description: string | null;
	status: string;
	checkboxes: unknown;
	createdAt: string | Date;
	executions?: Array<{
		id: string;
		status: string;
		createdAt: string | Date;
	}>;
	userStory?: {
		id: string;
		title: string;
		identifier?: string | null;
	} | null;
	storyTask?: {
		id: string;
		title: string;
	} | null;
}

interface WeavePlanListProps {
	plans: WeavePlan[];
	isLoading: boolean;
	preferredLocalProvider?: "KANBAN_LOCAL" | null;
	/** True while a plan is being created/generated by the Pattern agent */
	isGenerating?: boolean;
	/** Progress message while generating */
	planProgress?: string;
	onSelectExecution: (executionId: string) => void;
	repoUrl?: string;
	/** When set, this plan is auto-expanded (e.g. newly created) */
	highlightPlanId?: string;
	/** Story context available for creating a plan from feature data */
	storyContext?: {
		title: string;
		description?: string;
		acceptanceCriteria?: string;
	};
	/** Callback to create a plan from feature context */
	onCreateFromFeature?: () => void;
	/** Called when plan generation (re)starts so the parent can resume polling */
	onPlanGenerationStarted?: (planId: string) => void;
}

const AVAILABLE_AGENTS = [
	"thread",
	"spindle",
	"shuttle",
	"weft",
	"warp",
] as const;

const STATUS_CONFIG: Record<
	string,
	{ label: string; color: string; icon: React.ReactNode }
> = {
	DRAFT: {
		label: "Draft",
		color: "bg-gray-500/10 text-gray-600 border-gray-500/20",
		icon: <ClockIcon className="size-3" />,
	},
	PENDING_APPROVAL: {
		label: "Pending Approval",
		color: "bg-yellow-500/10 text-yellow-600 border-yellow-500/20",
		icon: <AlertCircleIcon className="size-3" />,
	},
	NEEDS_REVISION: {
		label: "Revising...",
		color: "bg-orange-500/10 text-orange-600 border-orange-500/20",
		icon: <RefreshCwIcon className="size-3 animate-spin" />,
	},
	APPROVED: {
		label: "Approved",
		color: "bg-blue-500/10 text-blue-600 border-blue-500/20",
		icon: <CheckCircleIcon className="size-3" />,
	},
	RUNNING: {
		label: "Running",
		color: "bg-purple-500/10 text-purple-600 border-purple-500/20",
		icon: <Loader2Icon className="size-3 animate-spin" />,
	},
	COMPLETED: {
		label: "Completed",
		color: "bg-green-500/10 text-green-600 border-green-500/20",
		icon: <CheckCircleIcon className="size-3" />,
	},
	FAILED: {
		label: "Failed",
		color: "bg-red-500/10 text-red-600 border-red-500/20",
		icon: <XCircleIcon className="size-3" />,
	},
	CANCELLED: {
		label: "Cancelled",
		color: "bg-gray-500/10 text-gray-600 border-gray-500/20",
		icon: <XCircleIcon className="size-3" />,
	},
};

function generateStepId(): string {
	return `step-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

// Token cost estimation per agent type (rough averages based on agent complexity)
const AGENT_TOKEN_ESTIMATES: Record<string, number> = {
	thread: 4000, // planning / routing — lighter
	spindle: 8000, // analysis / code review
	shuttle: 12000, // code generation — heaviest
	weft: 6000, // integration / glue
	warp: 5000, // verification / testing
};
const DEFAULT_TOKENS_PER_STEP = 6000;
const COST_PER_1K_TOKENS = 0.003; // blended estimate (input + output)

function estimatePlanCost(steps: WeavePlanStep[]): {
	totalTokens: number;
	estimatedCost: number;
	label: string;
} {
	let totalTokens = 0;
	for (const step of steps) {
		const agentKey = step.agent?.toLowerCase() ?? "";
		totalTokens +=
			AGENT_TOKEN_ESTIMATES[agentKey] ?? DEFAULT_TOKENS_PER_STEP;
	}
	const estimatedCost = (totalTokens / 1000) * COST_PER_1K_TOKENS;

	let label: string;
	if (estimatedCost < 0.01) {
		label = "<$0.01";
	} else if (estimatedCost < 0.1) {
		label = `~$${estimatedCost.toFixed(2)}`;
	} else {
		label = `~$${estimatedCost.toFixed(2)}`;
	}

	return { totalTokens, estimatedCost, label };
}

/**
 * Wrapper for an execution button that may be disabled. A disabled `<button>`
 * swallows pointer events, so the tooltip trigger has to sit on this wrapper
 * rather than on the button itself — that is what the original `title`-bearing
 * `<div>` was doing too. When there is no reason to show (the button is
 * enabled), the wrapper renders as a plain `<div>` with no tooltip at all.
 *
 * The wrapper is not focusable and the button inside it cannot take focus
 * while disabled, so the reason also goes into an `sr-only` child — otherwise
 * the copy would be pointer-only.
 */
function DisabledExecutionHint({
	reason,
	children,
}: {
	reason: string | null;
	children: React.ReactNode;
}) {
	if (!reason) {
		return <div>{children}</div>;
	}
	return (
		<Tooltip>
			<TooltipTrigger asChild>
				<div>
					{children}
					<span className="sr-only">{reason}</span>
				</div>
			</TooltipTrigger>
			<TooltipContent>{reason}</TooltipContent>
		</Tooltip>
	);
}

export function WeavePlanList({
	plans,
	isLoading,
	preferredLocalProvider: _preferredLocalProvider,
	isGenerating = false,
	planProgress,
	onSelectExecution,
	repoUrl = "",
	highlightPlanId,
	storyContext,
	onCreateFromFeature,
	onPlanGenerationStarted,
}: WeavePlanListProps) {
	const tTooltips = useTranslations("tooltips.weave");
	const [expandedPlan, setExpandedPlan] = useState<string | null>(null);

	// Auto-expand the highlighted plan once it appears in the list
	const didHighlightRef = useRef<string | null>(null);
	useEffect(() => {
		if (
			highlightPlanId &&
			highlightPlanId !== didHighlightRef.current &&
			plans.some((p) => p.id === highlightPlanId)
		) {
			didHighlightRef.current = highlightPlanId;
			setExpandedPlan(highlightPlanId);
		}
	}, [highlightPlanId, plans]);
	const [editingPlan, setEditingPlan] = useState<string | null>(null);
	const [editedCheckboxes, setEditedCheckboxes] = useState<
		Record<string, WeavePlanStep[]>
	>({});
	const [feedbackByPlan, setFeedbackByPlan] = useState<
		Record<string, string>
	>({});
	// Store pre-revision checkboxes for plan diff view
	const [previousCheckboxesByPlan, setPreviousCheckboxesByPlan] = useState<
		Record<string, WeavePlanStep[]>
	>({});
	const [showDiffForPlan, setShowDiffForPlan] = useState<string | null>(null);
	// Per-step inline feedback notes (planId -> stepIndex -> note)
	const [stepNotes, setStepNotes] = useState<
		Record<string, Record<number, string>>
	>({});
	const { organizationId } = useOrganizationContext();
	const queryClient = useQueryClient();

	const getCheckboxesForPlan = useCallback(
		(plan: WeavePlan): WeavePlanStep[] => {
			if (editingPlan === plan.id && editedCheckboxes[plan.id]) {
				return editedCheckboxes[plan.id];
			}
			return Array.isArray(plan.checkboxes)
				? (plan.checkboxes as WeavePlanStep[])
				: [];
		},
		[editingPlan, editedCheckboxes],
	);

	const startEditing = useCallback((plan: WeavePlan) => {
		const steps = Array.isArray(plan.checkboxes)
			? (plan.checkboxes as WeavePlanStep[])
			: [];
		setEditedCheckboxes((prev) => ({
			...prev,
			[plan.id]: steps.map((s) => ({ ...s })),
		}));
		setEditingPlan(plan.id);
	}, []);

	const cancelEditing = useCallback(() => {
		if (editingPlan) {
			setEditedCheckboxes((prev) => {
				const next = { ...prev };
				delete next[editingPlan];
				return next;
			});
		}
		setEditingPlan(null);
	}, [editingPlan]);

	const updateStep = useCallback(
		(
			planId: string,
			stepIndex: number,
			field: keyof WeavePlanStep,
			value: string,
		) => {
			setEditedCheckboxes((prev) => {
				const steps = [...(prev[planId] || [])];
				if (steps[stepIndex]) {
					steps[stepIndex] = { ...steps[stepIndex], [field]: value };
				}
				return { ...prev, [planId]: steps };
			});
		},
		[],
	);

	const moveStep = useCallback(
		(planId: string, fromIndex: number, direction: "up" | "down") => {
			setEditedCheckboxes((prev) => {
				const steps = [...(prev[planId] || [])];
				const toIndex =
					direction === "up" ? fromIndex - 1 : fromIndex + 1;
				if (toIndex < 0 || toIndex >= steps.length) {
					return prev;
				}
				const temp = steps[fromIndex];
				steps[fromIndex] = steps[toIndex];
				steps[toIndex] = temp;
				return { ...prev, [planId]: steps };
			});
		},
		[],
	);

	const removeStep = useCallback((planId: string, stepIndex: number) => {
		setEditedCheckboxes((prev) => {
			const steps = [...(prev[planId] || [])];
			steps.splice(stepIndex, 1);
			return { ...prev, [planId]: steps };
		});
	}, []);

	const addStep = useCallback((planId: string) => {
		setEditedCheckboxes((prev) => {
			const steps = [...(prev[planId] || [])];
			steps.push({
				id: generateStepId(),
				text: "",
				agent: "thread",
				status: "pending",
			});
			return { ...prev, [planId]: steps };
		});
	}, []);

	const approvePlanMutation = useMutation({
		mutationFn: async (input: {
			planId: string;
			approved: boolean;
			feedback?: string;
		}) =>
			orpcClient.weave.plans.approve({
				planId: input.planId,
				organizationId: organizationId ?? null,
				approved: input.approved,
				feedback: input.feedback,
			}),
		onSuccess: (_data, variables) => {
			toast.success(
				variables.approved
					? `Plan approved — now choose ${getExecutionProviderLabel("BACKGROUND_AGENTS")} or ${getExecutionProviderLabel("KANBAN_LOCAL")}.`
					: "Plan sent back for changes!",
			);
			// Clean up editing state for this plan
			if (editingPlan === variables.planId) {
				setEditingPlan(null);
			}
			setEditedCheckboxes((prev) => {
				const next = { ...prev };
				delete next[variables.planId];
				return next;
			});
			queryClient.invalidateQueries({ queryKey: ["weave-plans"] });
		},
		onError: (error) =>
			toast.error(`Failed to update plan: ${error.message}`),
	});

	const revisePlanMutation = useMutation({
		mutationFn: async (input: {
			planId: string;
			feedback: string;
			currentCheckboxes: WeavePlanStep[];
		}) => {
			// Capture current checkboxes before revision for diff view
			setPreviousCheckboxesByPlan((prev) => ({
				...prev,
				[input.planId]: input.currentCheckboxes,
			}));
			return orpcClient.weave.plans.revise({
				planId: input.planId,
				organizationId: organizationId ?? null,
				feedback: input.feedback,
			});
		},
		onSuccess: () => {
			toast.success("Plan revision requested — Pattern is regenerating.");
			queryClient.invalidateQueries({ queryKey: ["weave-plans"] });
		},
		onError: (error) =>
			toast.error(`Failed to request revision: ${error.message}`),
	});

	const retryGenerationMutation = useMutation({
		mutationFn: async (input: { planId: string }) =>
			orpcClient.weave.plans.retryGeneration({
				planId: input.planId,
				organizationId: organizationId ?? null,
			}),
		onSuccess: (data) => {
			toast.success("Retrying plan generation…");
			queryClient.invalidateQueries({ queryKey: ["weave-plans"] });
			onPlanGenerationStarted?.(data.planId);
		},
		onError: (error) =>
			toast.error(`Failed to retry plan generation: ${error.message}`),
	});

	const deletePlanMutation = useMutation({
		mutationFn: async (input: { planId: string }) =>
			orpcClient.weave.plans.delete({
				planId: input.planId,
				organizationId: organizationId ?? null,
			}),
		onSuccess: () => {
			toast.success("Plan deleted");
			queryClient.invalidateQueries({ queryKey: ["weave-plans"] });
		},
		onError: (error) =>
			toast.error(`Failed to delete plan: ${error.message}`),
	});

	const updateCheckboxesMutation = useMutation({
		mutationFn: async (input: {
			planId: string;
			checkboxes: WeavePlanStep[];
		}) =>
			orpcClient.weave.plans.updateCheckboxes({
				planId: input.planId,
				organizationId: organizationId ?? null,
				checkboxes: input.checkboxes.map((s) => ({
					id: s.id,
					text: s.text,
					agent: s.agent as
						| "thread"
						| "spindle"
						| "shuttle"
						| "weft"
						| "warp",
					status: (s.status ?? "pending") as
						| "pending"
						| "in_progress"
						| "completed"
						| "failed"
						| "skipped",
				})),
			}),
		onSuccess: () => {
			toast.success("Plan steps saved");
			setEditingPlan(null);
			queryClient.invalidateQueries({ queryKey: ["weave-plans"] });
		},
		onError: (error) =>
			toast.error(`Failed to save steps: ${error.message}`),
	});

	const saveTemplateMutation = useMutation({
		mutationFn: async (input: { planId: string; name: string }) =>
			orpcClient.weave.templates.save({
				planId: input.planId,
				organizationId: organizationId ?? null,
				name: input.name,
			}),
		onSuccess: () => {
			toast.success("Plan saved as template");
		},
		onError: (error) =>
			toast.error(`Failed to save template: ${error.message}`),
	});

	const startExecutionMutation = useMutation({
		mutationFn: async (input: {
			planId: string;
			executionProvider: "BACKGROUND_AGENTS" | "KANBAN_LOCAL";
		}) => {
			if (!repoUrl) {
				throw new Error(
					"No repository URL configured. Please set up the project repository first.",
				);
			}
			return orpcClient.weave.executions.start({
				planId: input.planId,
				organizationId: organizationId ?? null,
				repoUrl,
				targetBranch: "main",
				executionProvider: input.executionProvider,
			});
		},
		onSuccess: (data, variables) => {
			if (variables.executionProvider === "KANBAN_LOCAL") {
				toast.success(
					`Queued for ${getExecutionProviderLabel("KANBAN_LOCAL")}`,
					{
						description:
							"Run `fabric-kanban` in your repository to pull queued items.",
					},
				);
			} else {
				toast.success(
					`Delegated to ${getExecutionProviderLabel("BACKGROUND_AGENTS")}!`,
				);
			}
			queryClient.invalidateQueries({ queryKey: ["weave-plans"] });
			onSelectExecution(data.executionId);
		},
		onError: (error) =>
			toast.error(`Failed to start execution: ${error.message}`),
	});

	const hasActivePlans = plans.some(
		(p) => !["CANCELLED", "FAILED", "COMPLETED"].includes(p.status),
	);

	// Probe for a locally running fabric-kanban runtime while an approved
	// plan's execute actions are visible. Informational only — the Local
	// development button is never disabled by this probe.
	const hasApprovedPlan = plans.some((p) => p.status === "APPROVED");
	const kanbanRuntimeDetection = useKanbanRuntimeDetected(hasApprovedPlan);

	if (isLoading) {
		return (
			<div className="flex items-center justify-center h-full">
				<Loader2Icon className="size-8 animate-spin text-muted-foreground" />
			</div>
		);
	}

	if (plans.length === 0 && !isGenerating) {
		return (
			<div className="flex flex-col items-center justify-center h-full py-12 text-center">
				<GitBranchIcon className="size-12 text-muted-foreground mb-4" />
				<h3 className="text-lg font-medium mb-2">No Plans Yet</h3>
				<p className="text-sm text-muted-foreground max-w-sm mb-4">
					Create your first weave plan to start using multi-agent
					orchestration.
				</p>
				{storyContext && onCreateFromFeature && (
					<Button className="gap-2" onClick={onCreateFromFeature}>
						<PlayIcon className="size-4" />
						Create Plan from Feature
					</Button>
				)}
			</div>
		);
	}

	return (
		<div className="h-full overflow-y-auto">
			<div className="space-y-3 p-1 pr-2">
				{storyContext && onCreateFromFeature && !isGenerating && (
					<div className="flex justify-end">
						<Button
							size="sm"
							variant="outline"
							className="gap-1.5"
							onClick={onCreateFromFeature}
							disabled={hasActivePlans}
							title={
								hasActivePlans
									? "A plan already exists. Cancel or wait for it to complete before creating a new one."
									: undefined
							}
						>
							<PlusIcon className="size-3.5" />
							Create Plan from Feature
						</Button>
					</div>
				)}
				{isGenerating && (
					<Card className="p-5 border-primary/20 bg-primary/5">
						<div className="flex items-center gap-3">
							<Loader2Icon className="size-5 text-primary animate-spin shrink-0" />
							<div className="min-w-0">
								<p className="text-sm font-medium text-primary">
									{planProgress || "Generating plan..."}
								</p>
								<p className="text-xs text-muted-foreground mt-0.5">
									Pattern agent is analyzing your feature and
									creating an execution plan
								</p>
							</div>
						</div>
					</Card>
				)}
				{plans.map((plan) => {
					const planCheckboxes = getCheckboxesForPlan(plan);
					const status =
						STATUS_CONFIG[plan.status] || STATUS_CONFIG.DRAFT;
					const isExpanded = expandedPlan === plan.id;
					const canApprove = plan.status === "PENDING_APPROVAL";
					const canExecute = plan.status === "APPROVED";
					const isStandalonePlan = !plan.userStory;
					const disableBackgroundAgents =
						canExecute && isStandalonePlan;
					const isEditing = editingPlan === plan.id;
					const latestExecution = plan.executions?.[0];

					return (
						<Card
							key={plan.id}
							className={cn(
								"p-4 cursor-pointer transition-shadow hover:shadow-md",
								isExpanded && "ring-2 ring-violet-500",
							)}
							onClick={() => {
								if (!isEditing) {
									setExpandedPlan(
										isExpanded ? null : plan.id,
									);
								}
							}}
						>
							<div className="flex items-start justify-between gap-4">
								<div className="flex-1 min-w-0 overflow-hidden">
									<p
										className="font-medium truncate"
										title={plan.name}
									>
										{plan.name}
									</p>
									{plan.description && (
										<p
											className={cn(
												"text-sm text-muted-foreground mt-1 break-words",
												!isExpanded && "line-clamp-2",
											)}
										>
											{plan.description}
										</p>
									)}
									{(plan.userStory || plan.storyTask) && (
										<div className="flex items-center gap-1.5 mt-1.5">
											{plan.userStory && (
												<Badge
													variant="outline"
													className="text-[10px] bg-primary/5 border-primary/20 text-primary"
												>
													{plan.userStory.identifier
														? `${plan.userStory.identifier} `
														: ""}
													{plan.userStory.title
														.length > 40
														? `${plan.userStory.title.slice(0, 40)}...`
														: plan.userStory.title}
												</Badge>
											)}
											{plan.storyTask && (
												<Badge
													variant="outline"
													className="text-[10px] bg-muted"
												>
													Task:{" "}
													{plan.storyTask.title
														.length > 30
														? `${plan.storyTask.title.slice(0, 30)}...`
														: plan.storyTask.title}
												</Badge>
											)}
										</div>
									)}
									<div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground flex-wrap">
										<Badge
											variant="outline"
											className={cn(
												"text-[10px]",
												status.color,
											)}
										>
											<span className="flex items-center gap-1">
												{status.icon}
												{status.label}
											</span>
										</Badge>
										<span>
											{planCheckboxes.length} steps
										</span>
										<span>•</span>
										<span>
											Created{" "}
											{new Date(
												plan.createdAt,
											).toLocaleDateString()}
										</span>
										{latestExecution && (
											<span>
												Latest: {latestExecution.status}
											</span>
										)}
									</div>
								</div>

								<div className="flex items-center gap-2 shrink-0">
									{canApprove && !isEditing && (
										<>
											<Badge
												variant="outline"
												className="rounded-full border-muted-foreground/20 px-2 py-0.5 text-[10px] text-muted-foreground"
												title={`Estimated ${Math.round(estimatePlanCost(planCheckboxes).totalTokens / 1000)}k tokens`}
											>
												{
													estimatePlanCost(
														planCheckboxes,
													).label
												}{" "}
												est.
											</Badge>
											<Button
												size="sm"
												variant="outline"
												className="gap-1"
												onClick={(e) => {
													e.stopPropagation();
													approvePlanMutation.mutate({
														planId: plan.id,
														approved: true,
														feedback:
															feedbackByPlan[
																plan.id
															],
													});
												}}
												disabled={
													approvePlanMutation.isPending
												}
											>
												<CheckCircleIcon className="size-3" />
												Approve
											</Button>
											<Button
												size="sm"
												variant="ghost"
												className="gap-1"
												onClick={(e) => {
													e.stopPropagation();
													const generalFeedback =
														feedbackByPlan[
															plan.id
														]?.trim() || "";
													// Aggregate per-step notes
													const planNotes =
														stepNotes[plan.id];
													const stepFeedbackLines: string[] =
														[];
													if (planNotes) {
														const checkboxes =
															getCheckboxesForPlan(
																plan,
															);
														for (const [
															idx,
															note,
														] of Object.entries(
															planNotes,
														)) {
															if (note.trim()) {
																const step =
																	checkboxes[
																		Number(
																			idx,
																		)
																	];
																stepFeedbackLines.push(
																	`Step ${Number(idx) + 1}${step ? ` (${step.agent})` : ""}: ${note.trim()}`,
																);
															}
														}
													}
													const combinedFeedback = [
														generalFeedback,
														stepFeedbackLines.length >
														0
															? `\nPer-step feedback:\n${stepFeedbackLines.join("\n")}`
															: "",
													]
														.filter(Boolean)
														.join("\n");
													if (
														!combinedFeedback.trim()
													) {
														toast.error(
															"Please provide feedback describing what to change.",
														);
														return;
													}
													revisePlanMutation.mutate({
														planId: plan.id,
														feedback:
															combinedFeedback,
														currentCheckboxes:
															getCheckboxesForPlan(
																plan,
															),
													});
													// Clear step notes after submission
													setStepNotes((prev) => {
														const next = {
															...prev,
														};
														delete next[plan.id];
														return next;
													});
												}}
												disabled={
													revisePlanMutation.isPending
												}
											>
												<RefreshCwIcon className="size-3" />
												Revise
											</Button>
											<Button
												size="sm"
												variant="ghost"
												className="gap-1 text-red-600"
												onClick={(e) => {
													e.stopPropagation();
													approvePlanMutation.mutate({
														planId: plan.id,
														approved: false,
													});
												}}
												disabled={
													approvePlanMutation.isPending
												}
											>
												<XCircleIcon className="size-3" />
												Cancel
											</Button>
										</>
									)}
									{canExecute && (
										<>
											<DisabledExecutionHint
												reason={
													!repoUrl
														? tTooltips(
																"repoUrlRequired",
															)
														: disableBackgroundAgents
															? tTooltips(
																	"backgroundAgentsUnavailable",
																)
															: null
												}
											>
												<Button
													size="sm"
													className="gap-1"
													onClick={(e) => {
														e.stopPropagation();
														startExecutionMutation.mutate(
															{
																planId: plan.id,
																executionProvider:
																	"BACKGROUND_AGENTS",
															},
														);
													}}
													disabled={
														startExecutionMutation.isPending ||
														!repoUrl ||
														disableBackgroundAgents
													}
												>
													<PlayIcon className="size-3" />
													{getExecutionProviderLabel(
														"BACKGROUND_AGENTS",
													)}
												</Button>
											</DisabledExecutionHint>
											<DisabledExecutionHint
												reason={
													!repoUrl
														? tTooltips(
																"repoUrlRequired",
															)
														: null
												}
											>
												<Button
													size="sm"
													variant="outline"
													className="gap-1"
													onClick={(e) => {
														e.stopPropagation();
														startExecutionMutation.mutate(
															{
																planId: plan.id,
																executionProvider:
																	"KANBAN_LOCAL",
															},
														);
													}}
													disabled={
														startExecutionMutation.isPending ||
														!repoUrl
													}
												>
													<PlayIcon className="size-3" />
													{getExecutionProviderLabel(
														"KANBAN_LOCAL",
													)}
												</Button>
											</DisabledExecutionHint>
										</>
									)}
									{plan.status === "FAILED" && (
										<Button
											size="sm"
											variant="outline"
											className="gap-1"
											onClick={(e) => {
												e.stopPropagation();
												retryGenerationMutation.mutate({
													planId: plan.id,
												});
											}}
											disabled={
												retryGenerationMutation.isPending
											}
										>
											<RefreshCwIcon className="size-3" />
											Retry generation
										</Button>
									)}
									{(plan.status === "COMPLETED" ||
										plan.status === "APPROVED" ||
										plan.status === "RUNNING") && (
										<Button
											size="sm"
											variant="ghost"
											className="gap-1 text-muted-foreground"
											onClick={(e) => {
												e.stopPropagation();
												saveTemplateMutation.mutate({
													planId: plan.id,
													name: plan.name,
												});
											}}
											disabled={
												saveTemplateMutation.isPending
											}
											title="Save as reusable template"
										>
											<BookmarkPlusIcon className="size-3" />
											Save Template
										</Button>
									)}
									{plan.status !== "RUNNING" && (
										<AlertDialog>
											<AlertDialogTrigger asChild>
												<Button
													size="icon"
													variant="ghost"
													className="size-7 text-muted-foreground hover:text-destructive"
													onClick={(e) =>
														e.stopPropagation()
													}
													disabled={
														deletePlanMutation.isPending
													}
													aria-label="Delete plan"
													title="Delete plan"
												>
													<Trash2Icon className="size-3.5" />
												</Button>
											</AlertDialogTrigger>
											<AlertDialogContent
												onClick={(e) =>
													e.stopPropagation()
												}
											>
												<AlertDialogHeader>
													<AlertDialogTitle>
														Delete this plan?
													</AlertDialogTitle>
													<AlertDialogDescription>
														This permanently deletes
														“{plan.name}” and its
														execution history. This
														cannot be undone.
													</AlertDialogDescription>
												</AlertDialogHeader>
												<AlertDialogFooter>
													<AlertDialogCancel>
														Cancel
													</AlertDialogCancel>
													<AlertDialogAction
														variant="destructive"
														onClick={() =>
															deletePlanMutation.mutate(
																{
																	planId: plan.id,
																},
															)
														}
													>
														Delete
													</AlertDialogAction>
												</AlertDialogFooter>
											</AlertDialogContent>
										</AlertDialog>
									)}
								</div>
							</div>

							{isExpanded && (
								<div className="mt-4 overflow-hidden border-t pt-4">
									{canExecute &&
										(() => {
											const estimate =
												estimatePlanCost(
													planCheckboxes,
												);
											return (
												<div className="mb-4 rounded-xl border border-primary/15 bg-primary/[0.04] p-3 text-sm text-muted-foreground">
													<div className="flex items-start justify-between gap-3">
														<div>
															<p className="font-medium text-foreground">
																This plan is
																approved and
																ready for
																delegation.
															</p>
															<p className="mt-1 leading-6">
																{isStandalonePlan ? (
																	<>
																		This
																		standalone
																		plan is
																		ready
																		for
																		local
																		execution.
																		Use{" "}
																		<span className="text-foreground">
																			{getExecutionProviderLabel(
																				"KANBAN_LOCAL",
																			)}
																		</span>{" "}
																		to run
																		in your
																		checked-out
																		repository
																		through{" "}
																		{getExecutionProviderPlatformLabel(
																			"KANBAN_LOCAL",
																		)}
																		.{" "}
																		{getExecutionProviderLabel(
																			"BACKGROUND_AGENTS",
																		)}{" "}
																		are
																		currently
																		available
																		only for
																		feature-linked
																		plans.
																	</>
																) : (
																	<>
																		Choose{" "}
																		<span className="text-foreground">
																			{getExecutionProviderLabel(
																				"BACKGROUND_AGENTS",
																			)}
																		</span>{" "}
																		to hand
																		work off
																		to
																		Fabric-managed
																		remote
																		execution,
																		or{" "}
																		<span className="text-foreground">
																			{getExecutionProviderLabel(
																				"KANBAN_LOCAL",
																			)}
																		</span>{" "}
																		to run
																		it in
																		your
																		checked-out
																		repository
																		through{" "}
																		{getExecutionProviderPlatformLabel(
																			"KANBAN_LOCAL",
																		)}
																		.
																	</>
																)}
															</p>
															<p className="mt-1 leading-6">
																Run
																fabric-kanban
																locally to pull
																queued work.
															</p>
															{kanbanRuntimeDetection ===
																"not-detected" && (
																<p className="mt-2 flex items-start gap-1.5">
																	<AlertCircleIcon
																		className="mt-0.5 size-3.5 shrink-0 text-yellow-600"
																		aria-hidden="true"
																	/>
																	<span>
																		{
																			"Local fabric-kanban runtime not detected — run `fabric-kanban` in your repository to pull queued work."
																		}
																	</span>
																</p>
															)}
														</div>
														<Badge
															variant="outline"
															className="shrink-0 rounded-full border-primary/20 bg-primary/5 px-2.5 py-1 text-xs text-primary"
															title={`Estimated ${Math.round(estimate.totalTokens / 1000)}k tokens across ${planCheckboxes.length} steps`}
														>
															{estimate.label}{" "}
															est.
														</Badge>
													</div>
												</div>
											);
										})()}
									{canApprove && !isEditing && (
										<div className="mb-4 space-y-2">
											<h5 className="text-sm font-medium">
												Reviewer feedback
											</h5>
											<Textarea
												value={
													feedbackByPlan[plan.id] ||
													""
												}
												onChange={(e) =>
													setFeedbackByPlan(
														(prev) => ({
															...prev,
															[plan.id]:
																e.target.value,
														}),
													)
												}
												onClick={(e) =>
													e.stopPropagation()
												}
												placeholder="Describe what to change — Pattern will regenerate the plan with your feedback"
												className="min-h-24"
											/>
											<p className="text-xs text-muted-foreground">
												You can also add per-step notes
												below each step for targeted
												feedback.
											</p>
										</div>
									)}

									<div className="flex items-center justify-between mb-2">
										<h5 className="text-sm font-medium">
											Steps:
										</h5>
										{canApprove && !isEditing && (
											<Button
												size="sm"
												variant="ghost"
												className="gap-1 text-xs"
												onClick={(e) => {
													e.stopPropagation();
													startEditing(plan);
												}}
											>
												<PencilIcon className="size-3" />
												Edit Plan
											</Button>
										)}
									</div>

									{isEditing ? (
										<div className="space-y-2">
											{planCheckboxes.map(
												(step, index) => (
													<div
														key={step.id}
														className="flex items-center gap-2 text-sm"
													>
														<div className="flex flex-col">
															<Button
																size="icon"
																variant="ghost"
																className="size-6"
																disabled={
																	index === 0
																}
																onClick={(
																	e,
																) => {
																	e.stopPropagation();
																	moveStep(
																		plan.id,
																		index,
																		"up",
																	);
																}}
															>
																<ChevronUpIcon className="size-3" />
															</Button>
															<Button
																size="icon"
																variant="ghost"
																className="size-6"
																disabled={
																	index ===
																	planCheckboxes.length -
																		1
																}
																onClick={(
																	e,
																) => {
																	e.stopPropagation();
																	moveStep(
																		plan.id,
																		index,
																		"down",
																	);
																}}
															>
																<ChevronDownIcon className="size-3" />
															</Button>
														</div>
														<span className="text-muted-foreground w-6 text-center shrink-0">
															{index + 1}.
														</span>
														<Input
															value={step.text}
															onChange={(e) =>
																updateStep(
																	plan.id,
																	index,
																	"text",
																	e.target
																		.value,
																)
															}
															onClick={(e) =>
																e.stopPropagation()
															}
															placeholder="Step description"
															className="flex-1 h-8 text-sm"
														/>
														<select
															value={step.agent}
															onChange={(e) =>
																updateStep(
																	plan.id,
																	index,
																	"agent",
																	e.target
																		.value,
																)
															}
															onClick={(e) =>
																e.stopPropagation()
															}
															className="h-8 rounded-md border border-input bg-background px-2 text-xs"
														>
															{AVAILABLE_AGENTS.map(
																(agent) => (
																	<option
																		key={
																			agent
																		}
																		value={
																			agent
																		}
																	>
																		{agent}
																	</option>
																),
															)}
														</select>
														<Button
															size="icon"
															variant="ghost"
															className="size-7 text-muted-foreground hover:text-red-600 shrink-0"
															onClick={(e) => {
																e.stopPropagation();
																removeStep(
																	plan.id,
																	index,
																);
															}}
														>
															<Trash2Icon className="size-3" />
														</Button>
													</div>
												),
											)}

											<Button
												size="sm"
												variant="outline"
												className="gap-1 w-full mt-2 text-xs"
												onClick={(e) => {
													e.stopPropagation();
													addStep(plan.id);
												}}
											>
												<PlusIcon className="size-3" />
												Add Step
											</Button>

											<div className="flex items-center justify-end gap-2 pt-3 border-t mt-3">
												<Button
													size="sm"
													variant="ghost"
													onClick={(e) => {
														e.stopPropagation();
														cancelEditing();
													}}
												>
													Cancel
												</Button>
												<Button
													size="sm"
													variant="outline"
													className="gap-1"
													disabled={
														updateCheckboxesMutation.isPending
													}
													onClick={(e) => {
														e.stopPropagation();
														const edited =
															editedCheckboxes[
																plan.id
															];
														if (!edited) {
															return;
														}
														const hasEmpty =
															edited.some(
																(s) =>
																	!s.text.trim(),
															);
														if (hasEmpty) {
															toast.error(
																"All steps must have a description",
															);
															return;
														}
														updateCheckboxesMutation.mutate(
															{
																planId: plan.id,
																checkboxes:
																	edited,
															},
														);
													}}
												>
													<CheckCircleIcon className="size-3" />
													Save Changes
												</Button>
											</div>
										</div>
									) : (
										<div className="space-y-2">
											{previousCheckboxesByPlan[
												plan.id
											] && (
												<button
													type="button"
													onClick={(e) => {
														e.stopPropagation();
														setShowDiffForPlan(
															showDiffForPlan ===
																plan.id
																? null
																: plan.id,
														);
													}}
													className="text-xs text-primary hover:underline"
												>
													{showDiffForPlan === plan.id
														? "Hide changes"
														: "Show changes from previous version"}
												</button>
											)}
											{showDiffForPlan === plan.id &&
												previousCheckboxesByPlan[
													plan.id
												] && (
													<div className="rounded-lg border border-border/60 bg-muted/20 p-2 space-y-1 mb-2">
														<p className="text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
															Previous version
														</p>
														{previousCheckboxesByPlan[
															plan.id
														].map(
															(prevStep, idx) => {
																const currentStep =
																	planCheckboxes[
																		idx
																	];
																const isChanged =
																	!currentStep ||
																	currentStep.text !==
																		prevStep.text ||
																	currentStep.agent !==
																		prevStep.agent;
																return (
																	<div
																		key={
																			prevStep.id
																		}
																		className={cn(
																			"flex items-start gap-2 text-xs",
																			isChanged
																				? "text-destructive line-through opacity-60"
																				: "text-muted-foreground",
																		)}
																	>
																		<span className="w-4 shrink-0">
																			{idx +
																				1}
																			.
																		</span>
																		<span className="flex-1 min-w-0 break-words">
																			{
																				prevStep.text
																			}
																		</span>
																		<span className="text-[10px] shrink-0">
																			{
																				prevStep.agent
																			}
																		</span>
																	</div>
																);
															},
														)}
													</div>
												)}
											<div className="max-h-64 overflow-y-auto overflow-x-hidden space-y-1.5 pr-3">
												{planCheckboxes.map(
													(step, index) => {
														const prevSteps =
															previousCheckboxesByPlan[
																plan.id
															];
														const prevStep =
															prevSteps?.[index];
														const isNew =
															prevSteps &&
															!prevStep;
														const isModified =
															prevStep &&
															(prevStep.text !==
																step.text ||
																prevStep.agent !==
																	step.agent);
														const noteValue =
															stepNotes[
																plan.id
															]?.[index] ?? "";
														return (
															<div
																key={step.id}
																className={cn(
																	"text-sm",
																	isNew &&
																		"bg-green-500/10 rounded px-1 -mx-1",
																	isModified &&
																		"bg-blue-500/10 rounded px-1 -mx-1",
																)}
															>
																<div className="flex items-start gap-2">
																	<span className="text-muted-foreground w-6 shrink-0 pt-0.5">
																		{index +
																			1}
																		.
																	</span>
																	<span className="flex-1 min-w-0 break-words">
																		{
																			step.text
																		}
																	</span>
																	<div className="flex items-center gap-1 shrink-0 mt-0.5">
																		{isNew && (
																			<Badge
																				variant="outline"
																				className="text-[9px] bg-green-500/10 border-green-500/20 text-green-600 px-1"
																			>
																				new
																			</Badge>
																		)}
																		{isModified && (
																			<Badge
																				variant="outline"
																				className="text-[9px] bg-blue-500/10 border-blue-500/20 text-blue-600 px-1"
																			>
																				changed
																			</Badge>
																		)}
																		<Badge
																			variant="outline"
																			className="text-xs"
																		>
																			{
																				step.agent
																			}
																		</Badge>
																	</div>
																</div>
																{canApprove && (
																	<div className="ml-8 mt-1">
																		<Input
																			value={
																				noteValue
																			}
																			onChange={(
																				e,
																			) => {
																				e.stopPropagation();
																				setStepNotes(
																					(
																						prev,
																					) => ({
																						...prev,
																						[plan.id]:
																							{
																								...(prev[
																									plan
																										.id
																								] ||
																									{}),
																								[index]:
																									e
																										.target
																										.value,
																							},
																					}),
																				);
																			}}
																			onClick={(
																				e,
																			) =>
																				e.stopPropagation()
																			}
																			placeholder="Add note for this step..."
																			className="h-7 text-xs border-dashed"
																		/>
																	</div>
																)}
															</div>
														);
													},
												)}
											</div>
										</div>
									)}
								</div>
							)}
						</Card>
					);
				})}
			</div>
		</div>
	);
}
