/**
 * Registration + declared-constraint guard for the two conversation-capture
 * tables (Fizzy #2228).
 *
 * NO DATABASE REQUIRED — this suite reads the checked-in sources. The
 * behavioural half, which needs a real Postgres to prove the constraints are
 * enforced rather than merely written down, lives in
 * `conversation-capture-constraints.test.ts`.
 *
 * Three registrations have to move together and none of them fails loudly:
 *
 *   - `PROJECT_SCOPED_TABLES` / `USER_OWNED_TABLES` in `src/tenant-db.ts`.
 *     `getTenantFilter` returns null for a model it does not recognise and
 *     `mergeWithTenantFilter` then passes the WHERE through UNFILTERED. It
 *     fails OPEN.
 *   - the allowlist in `scripts/apply-rls-direct.ts`, keyed on the PHYSICAL
 *     snake_case name. A PascalCase model name there targets no relation.
 *   - the `@@map` in `schema.prisma`, which is what decides whether the two
 *     above are talking about the same table at all.
 *
 * `rls-coverage.test.ts` catches an org-scoped model missing from the RLS
 * allowlist generically. This suite is the specific one: it names both tables,
 * so a rename that updates one file and not the others reports here as a
 * missing registration rather than as a table that silently lost its filter.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const read = (relative: string) =>
	readFileSync(resolve(__dirname, "..", relative), "utf-8");

const schemaSrc = read("prisma/schema.prisma");
const tenantDbSrc = read("src/tenant-db.ts");
const applyRlsSrc = read("scripts/apply-rls-direct.ts");

const ownerKeyMigration = read(
	"prisma/migrations/20260826120000_project_context_owner_key/migration.sql",
);
const ownerUniqueMigration = read(
	"prisma/migrations/20260826120100_project_context_owner_identity_unique/migration.sql",
);
const captureMigration = read(
	"prisma/migrations/20260826120200_add_project_context_conversation_capture/migration.sql",
);

interface CaptureTable {
	model: string;
	physical: string;
}

const CAPTURE_TABLES: CaptureTable[] = [
	{
		model: "ProjectContextConversationBundle",
		physical: "project_context_conversation_bundle",
	},
	{
		model: "ProjectContextConversationClaim",
		physical: "project_context_conversation_claim",
	},
];

/** The body of one `model X { ... }` block. */
function modelBody(schema: string, model: string): string {
	const start = schema.indexOf(`model ${model} {`);
	expect(
		start,
		`model ${model} is missing from schema.prisma`,
	).toBeGreaterThan(-1);
	const end = schema.indexOf("\n}", start);
	return schema.slice(start, end);
}

describe.each(CAPTURE_TABLES)(
	"$model tenant registration",
	({ model, physical }) => {
		it("maps to its physical snake_case name", () => {
			expect(modelBody(schemaSrc, model)).toContain(
				`@@map("${physical}")`,
			);
		});

		it("is project-scoped in tenant-db, on projectId", () => {
			// The map is keyed on the MODEL name — that is what Prisma's
			// extension sees at query time — while the RLS allowlist below is
			// keyed on the physical name. Both are asserted so a rename cannot
			// satisfy one and quietly break the other.
			expect(tenantDbSrc).toMatch(
				new RegExp(`^\\s*${model}: "projectId",`, "m"),
			);
		});

		it("is tenant-filtered as user-owned in tenant-db", () => {
			const userOwned =
				tenantDbSrc.match(
					/const USER_OWNED_TABLES = new Set\(\[([\s\S]*?)\]\);/,
				)?.[1] ?? "";
			expect(userOwned).toContain(`"${model}"`);
		});

		it("has a user_owned RLS policy under its physical name", () => {
			// Physical name, not the model name: a PascalCase entry here
			// targets no relation, and the policy is silently never created.
			const entry = new RegExp(
				`name:\\s*"${physical}"\\s*,\\s*\\n?\\s*policy:\\s*"user_owned"`,
			);
			expect(applyRlsSrc).toMatch(entry);
		});

		it("carries both tenant columns and the generated owner identity", () => {
			const body = modelBody(schemaSrc, model);
			expect(body).toMatch(/^\s*userId\s+String\?/m);
			expect(body).toMatch(/^\s*organizationId\s+String\?/m);
			expect(body).toMatch(/^\s*ownerKey\s+String\?/m);
		});
	},
);

describe.each(CAPTURE_TABLES)(
	"$physical database-enforced ownership",
	({ physical }) => {
		it("resolves ownerKey from the tenant columns, generated by Postgres", () => {
			expect(captureMigration).toContain(
				`"ownerKey" TEXT GENERATED ALWAYS AS (COALESCE("organizationId", "userId")) STORED`,
			);
		});

		it("declares the tenant XOR CHECK the generated column depends on", () => {
			expect(captureMigration).toContain(
				`CONSTRAINT "${physical}_tenant_xor"`,
			);
			expect(captureMigration).toMatch(
				new RegExp(
					`CONSTRAINT "${physical}_tenant_xor"\\s*\\n?\\s*CHECK \\(\\("userId" IS NULL\\) <> \\("organizationId" IS NULL\\)\\)`,
				),
			);
		});

		it("keys its parent foreign key on project AND owner, not parentage alone", () => {
			// The whole point of the unit. A key over parentContextId alone —
			// or even over (parentContextId, projectId) — never compares
			// owners, so it admits an organization-owned child under a personal
			// parent. MATCH FULL so the check does not silently lapse if the
			// XOR CHECK above is ever relaxed and ownerKey becomes NULLable in
			// practice.
			expect(captureMigration).toContain(
				`ALTER TABLE "${physical}" ADD CONSTRAINT "${physical}_owner_fkey" FOREIGN KEY ("parentContextId", "projectId", "ownerKey") REFERENCES "project_context"("id", "projectId", "ownerKey") MATCH FULL ON DELETE CASCADE ON UPDATE NO ACTION;`,
			);
		});

		it("cascades from its parent context", () => {
			expect(captureMigration).toContain(
				`ALTER TABLE "${physical}" ADD CONSTRAINT "${physical}_parentContextId_fkey" FOREIGN KEY ("parentContextId") REFERENCES "project_context"("id") ON DELETE CASCADE`,
			);
		});
	},
);

describe("project_context owner identity", () => {
	it("adds ownerKey as a stored generated column", () => {
		expect(ownerKeyMigration).toContain(
			`ALTER TABLE "project_context"\n  ADD COLUMN "ownerKey" TEXT GENERATED ALWAYS AS (COALESCE("organizationId", "userId")) STORED;`,
		);
	});

	it("builds the referenced unique index CONCURRENTLY, as the only statement in its migration", () => {
		expect(ownerUniqueMigration).toContain(
			`CREATE UNIQUE INDEX CONCURRENTLY "project_context_id_projectId_ownerKey_key"`,
		);
		// Prisma wraps a multi-statement migration in a transaction, and
		// CONCURRENTLY cannot run inside one (SQLSTATE 25001). Counting
		// statement terminators is what stops a later edit adding a second.
		const statements = ownerUniqueMigration
			.split("\n")
			.filter((line) => !line.trim().startsWith("--"))
			.join("\n")
			.split(";")
			.filter((chunk) => chunk.trim().length > 0);
		expect(statements).toHaveLength(1);
	});

	it("declares the same unique in the Prisma schema, so a shadow diff does not read it as drift", () => {
		expect(modelBody(schemaSrc, "ProjectContext")).toContain(
			'@@unique([id, projectId, ownerKey], map: "project_context_id_projectId_ownerKey_key")',
		);
	});
});

describe("bundle ordering and the embedding lease", () => {
	const bundle = () =>
		modelBody(schemaSrc, "ProjectContextConversationBundle");

	it("orders bundles by when the conversation happened, not when capture ran", () => {
		expect(bundle()).toMatch(/^\s*bundleStartedAt\s+DateTime$/m);
		expect(bundle()).toContain(
			'@@index([parentContextId, bundleStartedAt], map: "project_context_conversation_bundle_parent_started_idx")',
		);
	});

	it("keeps the embedding lease separate from the confirmation", () => {
		// `embeddedAt` must never double as the claim: a crash between claiming
		// and the vector write would leave it non-null with no vector, and the
		// recovery pass — null embeddedAt, no live lease — would skip that row
		// forever.
		expect(bundle()).toMatch(/^\s*embeddingLeaseAt\s+DateTime\?$/m);
		expect(bundle()).toMatch(/^\s*embeddedAt\s+DateTime\?$/m);
	});
});

describe("the claim is the idempotency key", () => {
	it("is unique on (parentContextId, providerMessageId)", () => {
		expect(
			modelBody(schemaSrc, "ProjectContextConversationClaim"),
		).toContain(
			'@@unique([parentContextId, providerMessageId], map: "project_context_conversation_claim_message_key")',
		);
		expect(captureMigration).toContain(
			'CREATE UNIQUE INDEX "project_context_conversation_claim_message_key" ON "project_context_conversation_claim"("parentContextId", "providerMessageId");',
		);
	});

	it("records which bundle each claim was folded into", () => {
		expect(modelBody(schemaSrc, "ProjectContextConversationClaim")).toMatch(
			/^\s*bundleId\s+String\?$/m,
		);
	});
});

describe("back-relations", () => {
	it.each([
		["ProjectContext", "conversationBundles", "conversationClaims"],
		[
			"User",
			"projectContextConversationBundles",
			"projectContextConversationClaims",
		],
		[
			"Organization",
			"projectContextConversationBundles",
			"projectContextConversationClaims",
		],
	])("%s carries both", (model, bundleField, claimField) => {
		const body = modelBody(schemaSrc, model);
		expect(body).toMatch(
			new RegExp(
				`^\\s*${bundleField}\\s+ProjectContextConversationBundle\\[\\]`,
				"m",
			),
		);
		expect(body).toMatch(
			new RegExp(
				`^\\s*${claimField}\\s+ProjectContextConversationClaim\\[\\]`,
				"m",
			),
		);
	});
});
