/**
 * Local demonstration of the pm-sync table/image transforms (the bug fix
 * for "Tables and Images in Fabric Feature Content Are Not Synced to PM
 * Tools"). Runs the pure transform pipeline against synthetic Tiptap-
 * shaped descriptions for every supported PM tool and writes the rendered
 * output to a markdown file for visual inspection.
 *
 * Usage (from packages/temporal):
 *   pnpm tsx scripts/demo-pm-sync-transforms.ts
 *
 * Outputs:
 *   packages/temporal/scripts/.demo-output/pm-sync-transforms.md
 *
 * This script intentionally does NOT call the real S3 client — it stubs
 * `getStorageProvider()` so the output is deterministic and the demo
 * doesn't require MinIO credentials to be in scope. The transform code
 * paths exercised here are 100% identical to production.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Stub @repo/storage BEFORE importing the transforms so the storage
// provider returns deterministic signed URLs. Without this the script
// would need real S3 credentials in the env.
const __dirname = dirname(fileURLToPath(import.meta.url));

// In Node ESM we can't monkey-patch a workspace package import, so this
// script uses a small in-process function that mirrors the production
// resolver shape. The transforms module accepts a URL map directly — see
// `rewriteStoryMediaSourcesToSignedUrls` — so we never actually invoke
// `resolveStoryMediaSignedUrls` here.
async function main() {
	// Lazy-import so we control the bootstrap order.
	const {
		convertEmbeddedHtmlTablesToMarkdown,
		extractFizzyImages,
		extractStoryMediaKeysFromContent,
		looksFabricAuthored,
		restoreFizzyImages,
		rewriteStoryMediaSourcesToSignedUrls,
	} = await import("../src/activities/pm-integration/story-sync-media");
	const { extractFizzyTables, markdownToSimpleHtml, restoreFizzyTables } =
		await import("../src/activities/pm-integration/story-sync");

	const TIPTAP_TABLE_WITH_IMAGE_IN_CELL =
		'<table class="tiptap-table" style="min-width: 75px;"><colgroup><col style="min-width: 25px;"><col style="min-width: 25px;"></colgroup><tbody>' +
		'<tr><th colspan="1" rowspan="1"><p>Step</p></th><th colspan="1" rowspan="1"><p>Diagram</p></th></tr>' +
		'<tr><td colspan="1" rowspan="1"><p><strong>1</strong> — login</p></td><td colspan="1" rowspan="1"><p><img src="story-media/p/s/login-flow.png" data-s3-key="story-media/p/s/login-flow.png" alt="login flow"></p></td></tr>' +
		'<tr><td colspan="1" rowspan="1"><p>2 — redirect | wait</p></td><td colspan="1" rowspan="1"><p><em>none</em></p></td></tr>' +
		"</tbody></table>";

	const FABRIC_FEATURE_DESCRIPTION = [
		"# User Story",
		"",
		"As a customer, I want to **log in** via SSO so that I can access the",
		"dashboard without typing my password.",
		"",
		"## Acceptance Criteria",
		"",
		"- Given I am on the login screen",
		"- When I click _Sign in with Google_",
		"- Then I am redirected to the OAuth flow",
		"",
		"### Flow diagram",
		"",
		TIPTAP_TABLE_WITH_IMAGE_IN_CELL,
		"",
		"## Attachments",
		"",
		"![architecture overview](story-media/p/s/architecture.png)",
		"",
		'<p><a href="https://fabric.pro/app/acme/projects/p/stories/s">View in Fabric</a></p>',
	].join("\n");

	// Mock signed URLs (matches the shape `resolveStoryMediaSignedUrls`
	// would return for real S3 keys).
	const signedUrlMap = new Map<string, string>([
		[
			"story-media/p/s/login-flow.png",
			"https://signed.example.com/story-media/p/s/login-flow.png?Sig=A&Expires=1234",
		],
		[
			"story-media/p/s/architecture.png",
			"https://signed.example.com/story-media/p/s/architecture.png?Sig=B&Expires=1234",
		],
	]);

	const sections: string[] = [];
	sections.push("# PM Sync Transforms — Live Demo");
	sections.push("");
	sections.push(
		"Generated by `packages/temporal/scripts/demo-pm-sync-transforms.ts`. " +
			"Shows the output of the new transform pipeline for a representative " +
			"Fabric-authored feature description that contains a Tiptap table with " +
			"an inline image, a `## Attachments` markdown image block, and the " +
			"standard Fabric back-link.",
	);
	sections.push("");
	sections.push("## Input (raw `UserStory.description`)");
	sections.push("");
	sections.push("```html");
	sections.push(FABRIC_FEATURE_DESCRIPTION);
	sections.push("```");
	sections.push("");
	sections.push(
		`**Extracted story-media keys:** ${JSON.stringify(extractStoryMediaKeysFromContent(FABRIC_FEATURE_DESCRIPTION))}`,
	);
	sections.push(
		`**looksFabricAuthored:** ${looksFabricAuthored(FABRIC_FEATURE_DESCRIPTION)}`,
	);
	sections.push("");

	// ---- Fizzy (HTML, Lexxy editor) ----------------------------------------
	const { content: fizzyResolved, unresolvedKeys: fizzyUnresolved } =
		rewriteStoryMediaSourcesToSignedUrls(
			FABRIC_FEATURE_DESCRIPTION,
			signedUrlMap,
		);
	const { withTokens: fizzyTableTokens, tables: fizzyTables } =
		extractFizzyTables(fizzyResolved);
	const { withTokens: fizzyImgTokens, images: fizzyImages } =
		extractFizzyImages(fizzyTableTokens);
	const fizzyOut = restoreFizzyImages(
		restoreFizzyTables(markdownToSimpleHtml(fizzyImgTokens), fizzyTables),
		fizzyImages,
	);
	sections.push("## Output: Fizzy (Lexxy HTML)");
	sections.push("");
	sections.push("```html");
	sections.push(fizzyOut);
	sections.push("```");
	sections.push(
		`Unresolved story-media keys: ${JSON.stringify(fizzyUnresolved)}`,
	);
	sections.push("");

	// ---- Jira / Linear / GitHub / GitLab (markdown native) -----------------
	const { content: mdResolved, unresolvedKeys: mdUnresolved } =
		rewriteStoryMediaSourcesToSignedUrls(
			FABRIC_FEATURE_DESCRIPTION,
			signedUrlMap,
		);
	const mdOut = convertEmbeddedHtmlTablesToMarkdown(mdResolved);
	sections.push(
		"## Output: Jira / Linear / GitHub / GitLab (markdown native)",
	);
	sections.push("");
	sections.push("```markdown");
	sections.push(mdOut);
	sections.push("```");
	sections.push(
		`Unresolved story-media keys: ${JSON.stringify(mdUnresolved)}`,
	);
	sections.push("");

	// ---- ADO (System.Description with format: "Markdown") ------------------
	// Same pipeline as the markdown-native tools above.
	sections.push(
		'## Output: Azure DevOps (`System.Description`, `format: "Markdown"`)',
	);
	sections.push("");
	sections.push("```markdown");
	sections.push(mdOut);
	sections.push("```");
	sections.push("");

	// ---- Round-trip safety: pulled-from-PM HTML must pass through ----------
	const PULLED_HTML =
		"<p>Description from ADO.</p><table><tbody><tr><td>A</td><td>B</td></tr></tbody></table><p>Bottom.</p>";
	sections.push("## Round-trip safety: pulled-from-PM HTML passes through");
	sections.push("");
	sections.push("**Input (pulled-from-PM, no Tiptap markers):**");
	sections.push("");
	sections.push("```html");
	sections.push(PULLED_HTML);
	sections.push("```");
	sections.push(
		`**looksFabricAuthored:** ${looksFabricAuthored(PULLED_HTML)} (expected: \`false\`)`,
	);
	sections.push("");
	sections.push("**Output (byte-for-byte):**");
	sections.push("");
	sections.push("```html");
	sections.push(PULLED_HTML);
	sections.push("```");
	sections.push("");

	const outDir = resolve(__dirname, ".demo-output");
	mkdirSync(outDir, { recursive: true });
	const outPath = resolve(outDir, "pm-sync-transforms.md");
	writeFileSync(outPath, sections.join("\n"), "utf8");
	console.log(`Wrote demo output to ${outPath}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
