/**
 * Audit Log viewer — E2E coverage.
 *
 * Three scenarios from spec §13.5:
 *   1. Org admin opens `/app/<slug>/settings/audit-log`, applies a filter,
 *      and triggers a CSV export — the download fires with the right
 *      content-type / filename.
 *   2. A non-admin visiting the same URL sees the editorial-restraint
 *      forbidden panel and the sidebar entry is not present.
 *   3. The personal viewer at `/app/settings/audit-log` renders the
 *      current user's events with a locked actor chip showing their
 *      email.
 *
 * Test infrastructure notes:
 *   - This repo's Playwright project uses a single `storageState` cookie
 *     (`apps/web/tests/.auth/user.json`) generated by `auth.setup.ts`
 *     from `E2E_USER_EMAIL` / `E2E_USER_PASSWORD`. There are no
 *     pre-seeded role-specific fixtures (admin/viewer/non-member) in the
 *     repo today. Tests that require a known role gracefully skip if the
 *     seeded user does not satisfy the precondition — see the
 *     `admin-monitoring.spec.ts` precedent for this pattern.
 *   - The org slug is resolved at runtime by navigating to `/app` and
 *     reading the redirected URL. Tests skip if the user does not land
 *     in an org context (i.e. has no organization memberships).
 *   - When the user CAN navigate to the viewer but lacks org-admin
 *     privileges, the page renders the forbidden panel; we assert that
 *     panel and the missing sidebar entry.
 *
 * Run via `pnpm --filter web e2e tests/audit-log.spec.ts`.
 *
 * Spec: docs/audit-log/README.md §13.5.
 */
import { expect, test } from "@playwright/test";
import type { Page } from "@playwright/test";

const PERSONAL_AUDIT_URL = "/app/settings/audit-log";

/**
 * Resolve the current user's first org slug by following the post-login
 * redirect. Returns `null` when the user has no org membership.
 */
async function resolveOrgSlug(page: Page): Promise<string | null> {
	await page.goto("/app");
	await page.waitForLoadState("domcontentloaded");
	const url = page.url();
	// Personal-context URLs look like `/app` or `/app/settings/...`.
	// Org-context URLs look like `/app/<slug>` or `/app/<slug>/...`.
	const match = url.match(/\/app\/([^/?#]+)(?:[/?#]|$)/);
	if (!match) {
		return null;
	}
	const candidate = match[1];
	if (candidate === "settings" || candidate === "admin") {
		return null;
	}
	return candidate;
}

/**
 * Detect whether the currently-rendered audit log page is the forbidden
 * panel (non-admin direct navigation) or the actual viewer.
 */
async function isViewerForbidden(page: Page): Promise<boolean> {
	// The forbidden panel renders a destructive card with the
	// `settings.auditLog.forbidden.title` heading. The viewer renders
	// the SettingsHero followed by the filters bar.
	const forbiddenHeading = page.getByText("Access required", {
		exact: true,
	});
	return await forbiddenHeading.isVisible().catch(() => false);
}

test.describe("Audit Log viewer", () => {
	test("org admin filters and exports CSV", async ({ page }) => {
		const orgSlug = await resolveOrgSlug(page);
		if (!orgSlug) {
			// Seeded user has no org membership — cannot exercise the
			// org viewer path. Skip rather than fail.
			test.skip();
			return;
		}

		const auditUrl = `/app/${orgSlug}/settings/audit-log`;
		const response = await page.goto(auditUrl);
		// Migration not applied on this preview, or the layout 404'd —
		// skip gracefully so the suite is still meaningful when the
		// audit-log feature is rolled out incrementally.
		if (response?.status() === 404) {
			test.skip();
			return;
		}

		// Page heading uses the editorial SettingsHero. The h1 carries
		// the translated "Audit Log" title.
		const auditHeading = page.getByRole("heading", {
			level: 1,
			name: "Audit Log",
		});
		// If forbidden was rendered instead, the seeded user isn't an
		// admin — skip the export path.
		if (await isViewerForbidden(page)) {
			test.skip();
			return;
		}
		await expect(auditHeading).toBeVisible();

		// Apply a date filter via the "Last 7 days" preset. The chip
		// has aria-label "Filter by date range" and opens a popover.
		const dateChip = page.getByRole("button", {
			name: /Filter by date range/i,
		});
		// The chip may render as a Badge-styled button; fall back to
		// label-based locator if aria-label isn't reachable.
		const chipCount = await dateChip.count();
		if (chipCount > 0) {
			await dateChip.first().click();
			const preset = page.getByRole("button", { name: "Last 7 days" });
			if (await preset.isVisible().catch(() => false)) {
				await preset.click();
			} else {
				// Some chips close on outside click; press Escape to
				// keep the table state clean.
				await page.keyboard.press("Escape");
			}
		}

		// Wait for the table to settle after the filter change.
		await page.waitForLoadState("networkidle");

		// Trigger the export. The dropdown shows two options
		// ("Export as CSV" / "Export as NDJSON"). When the result set
		// is empty the button is disabled — in that case we cannot
		// drive the download path; skip the assertion.
		const exportButton = page.getByRole("button", {
			name: /Export audit log/i,
		});
		if (!(await exportButton.isVisible().catch(() => false))) {
			test.skip();
			return;
		}
		if (await exportButton.isDisabled().catch(() => true)) {
			test.skip();
			return;
		}
		await exportButton.click();

		const csvOption = page.getByRole("menuitem", {
			name: "Export as CSV",
		});
		await expect(csvOption).toBeVisible();

		// The download is driven by `URL.createObjectURL` + a synthetic
		// anchor click, so Playwright's `page.waitForEvent("download")`
		// captures it. We wait alongside the click.
		const [download] = await Promise.all([
			page.waitForEvent("download", { timeout: 15_000 }),
			csvOption.click(),
		]);

		// Filename matches the procedure's contract:
		// `audit-log-<organizationId|personal>-<ISO>.csv`.
		const filename = download.suggestedFilename();
		expect(filename).toMatch(/^audit-log-.*\.csv$/);
	});

	test("non-admin cannot reach the org viewer", async ({ page }) => {
		const orgSlug = await resolveOrgSlug(page);
		if (!orgSlug) {
			test.skip();
			return;
		}

		const auditUrl = `/app/${orgSlug}/settings/audit-log`;
		const response = await page.goto(auditUrl);
		if (response?.status() === 404) {
			test.skip();
			return;
		}

		// The inverse of the previous test: if the seeded user is an
		// admin, the forbidden panel never renders. Skip rather than
		// fail when we can't exercise the negative path.
		if (!(await isViewerForbidden(page))) {
			test.skip();
			return;
		}

		// Forbidden panel: destructive-styled card with editorial copy.
		await expect(page.getByText("Access required")).toBeVisible();
		await expect(
			page.getByText(
				"Only organization owners and admins can view the audit log.",
			),
		).toBeVisible();

		// Sidebar entry must not be visible when access is denied.
		// The settings sidebar renders nav items as anchors with the
		// menu-label text "Audit Log".
		const sidebarEntry = page
			.getByRole("navigation")
			.getByRole("link", { name: "Audit Log" });
		await expect(sidebarEntry).toHaveCount(0);
	});

	// TODO(audit-log a11y): wire up @axe-core/playwright to assert zero
	// accessibility violations on both viewer pages. The package is NOT
	// in apps/web/package.json today (only `vitest-axe` is, used for
	// component-level unit tests). To enable:
	//   1. pnpm --filter web add -D @axe-core/playwright
	//   2. Replace this fixme with:
	//        import AxeBuilder from "@axe-core/playwright";
	//        const results = await new AxeBuilder({ page }).analyze();
	//        expect(results.violations).toEqual([]);
	// Spec §8.5 / task 5.4 acceptance criteria.
	test.fixme(
		"axe-core scan on audit log viewer pages — @axe-core/playwright not installed",
		async () => {
			// Intentionally empty — deferred until @axe-core/playwright
			// is added as a dev dependency. See TODO above.
		},
	);

	test("personal viewer shows the caller's own events with a locked actor chip", async ({
		page,
	}) => {
		const response = await page.goto(PERSONAL_AUDIT_URL);
		// Account-area pages redirect to login when the auth cookie
		// expired. If we end up off the audit page, skip cleanly.
		if (response?.status() === 404) {
			test.skip();
			return;
		}
		if (!page.url().endsWith(PERSONAL_AUDIT_URL)) {
			test.skip();
			return;
		}

		await expect(
			page.getByRole("heading", { level: 1, name: "Audit Log" }),
		).toBeVisible();

		// Personal description copy: "Authentication, MFA, and personal-
		// context lifecycle events for your account."
		await expect(
			page.getByText(
				"Authentication, MFA, and personal-context lifecycle events for your account.",
			),
		).toBeVisible();

		// In personal mode the actor chip is a locked Badge whose
		// `title` attribute carries "Personal events". The badge body
		// shows "Actor: <email>". We assert the Badge presence; the
		// exact email is whatever the seeded auth user signed in as.
		const actorBadge = page.locator('[title="Personal events"]');
		await expect(actorBadge).toBeVisible();
		await expect(actorBadge).toContainText("Actor:");
	});
});
