/**
 * Picker-dialog cross-page handoff helper.
 *
 * When the chat surface can't resolve an active TipTap editor on the
 * current page (e.g. Nexus, Loom, or a feature page chat targeting a
 * document on a different page), the user picks a target via the
 * `InsertDiagramPickerDialog`. The picker navigates to that page; the
 * destination editor reads the consumer hook to discover the in-flight
 * intent and complete the insertion.
 *
 * sessionStorage is the right primitive here because:
 *   - It survives the `router.push` navigation (component state would
 *     not).
 *   - It is automatically scoped to the tab — picker -> target opens
 *     in the same tab, so we never cross-pollinate across tabs.
 *   - It is consumed exactly once on the destination page (read +
 *     remove), making the picker handoff at-most-once even under
 *     accidental page reloads in between.
 *
 * Spec sections:
 *   - § 10.4  Picker dialog cross-page idempotency
 *   - § 11 row 8  60-second expiry, telemetry event on timeout
 *   - § 17    Trust model — only server-validated cuids
 *             (`mcpConfigId`, `checkpointId`) go into the payload
 *
 * SSR safety: every entrypoint guards on `typeof window !== "undefined"`.
 * Calling from a server component is a no-op that returns the safe
 * default (`null` for reads, void for writes / expirations).
 */

import type { ChatSurface } from "./types";

/**
 * Hard cap on intent age before `consumePickerIntent` returns `null`.
 * Tracked as 60 seconds per spec § 11 row 8. Picked to give the user
 * time for a single-page navigation + editor boot without lingering
 * stale entries across longer pauses (which would risk inserting into
 * the wrong page after a navigation race).
 */
export const PICKER_INTENT_EXPIRY_MS = 60_000;

/** Storage-key prefix; suffix is the `diagramRequestId`. */
const PICKER_INTENT_STORAGE_PREFIX = "excalidraw-auto-insert:";

/**
 * Build the canonical storage key. Exported for tests and for the
 * Playwright spec, which asserts on the exact key in spec § 19.
 */
export function buildPickerIntentStorageKey(diagramRequestId: string): string {
	return `${PICKER_INTENT_STORAGE_PREFIX}${diagramRequestId}`;
}

/**
 * The "kind" of picker target. Matches the resolver target shape so
 * the consumer hook on the destination page can verify the intent's
 * target matches the page it just landed on.
 */
export type PickerIntentTargetKind = "document" | "story";

/**
 * Shape of the intent payload. The payload is JSON-encoded into
 * sessionStorage on write and JSON-decoded on read.
 *
 * Only `mcpConfigId` and `checkpointId` are server-validated values
 * (cuids that came back from the `createFromChat` procedure on a
 * previous step or from the MCP server's tool-result envelope). All
 * other fields are user-prompt-derived or client-side identifiers
 * (`diagramRequestId` is a UUID generated at picker click time).
 *
 * Per spec § 17: never include credentials or other arbitrary
 * user-typed text beyond `title` (which is derived from the user's
 * own prompt via `deriveDiagramTitle`).
 */
export interface PickerIntent {
	/**
	 * UUID generated by the picker at click time. The destination
	 * editor reads + consumes by this id; same id is used to fire
	 * `diagram_auto_insert_picker_timeout` telemetry if the intent
	 * expires before being consumed.
	 */
	diagramRequestId: string;
	/** The chat surface that opened the picker. Forwarded to telemetry. */
	surface: ChatSurface;
	/** Source project + organization the chat is scoped to. */
	projectId: string;
	organizationId: string;
	/**
	 * Scene JSON from the MCP `create_view` tool result. Stored
	 * verbatim — the destination page does NOT re-call the MCP server.
	 * Type is `unknown` because the upstream extractor (`McpAppFrame`)
	 * does the normalisation; we just shuttle it.
	 */
	elements: unknown;
	/** Optional view state from `create_view`. */
	appState?: unknown;
	/** Stable MCP scene handle — server-validated cuid. */
	checkpointId: string;
	/** Tenant's MCP config id — server-validated cuid. */
	mcpConfigId: string;
	/** Derived title (already passed through `deriveDiagramTitle`). */
	title: string;
	/** Whether the picker's target is a document or a story. */
	targetKind: PickerIntentTargetKind;
	/**
	 * The document or story id the user selected in the picker. The
	 * consumer hook on the destination page compares this to its own
	 * `documentId` / `storyId` prop to verify it landed on the
	 * intended page (defensive — guards against router races).
	 */
	targetId: string;
	/**
	 * `Date.now()` at write time. `consumePickerIntent` uses this to
	 * enforce the 60-second expiry.
	 */
	createdAt: number;
}

function isBrowserEnvironment(): boolean {
	return (
		typeof window !== "undefined" &&
		typeof window.sessionStorage !== "undefined"
	);
}

/**
 * Persist a picker intent so the destination editor can consume it
 * on mount. Idempotent — calling with the same `diagramRequestId`
 * replaces the previous entry.
 *
 * SSR no-op: returns immediately without throwing when called outside
 * a browser. The picker UI only runs client-side, so this is the
 * defensive belt-and-suspenders guard for accidental SSR import paths.
 */
export function writePickerIntent(intent: PickerIntent): void {
	if (!isBrowserEnvironment()) {
		return;
	}
	try {
		const key = buildPickerIntentStorageKey(intent.diagramRequestId);
		window.sessionStorage.setItem(key, JSON.stringify(intent));
	} catch {
		// sessionStorage may throw if the tab is in a partitioned/quota-
		// limited state (private browsing, full quota, etc.). Swallow
		// silently — the picker UX shouldn't crash on storage hiccups.
		// The destination page will fall back to opening the picker again.
	}
}

/**
 * Read + remove the intent for `diagramRequestId`. Returns:
 *   - The decoded intent if it exists AND is younger than 60 seconds.
 *   - `null` if no intent exists for that id.
 *   - `null` if the intent has expired (caller fires the
 *     `diagram_auto_insert_picker_timeout` telemetry — spec § 11 row 8).
 *
 * Always removes the storage entry as part of the read so the handoff
 * is at-most-once: a second consumer call returns `null`. This is the
 * design lever that makes the picker handoff safe under page reloads
 * (a reload would otherwise replay the insertion).
 *
 * SSR no-op: returns `null` when called outside a browser.
 */
export function consumePickerIntent(
	diagramRequestId: string,
): PickerIntent | null {
	if (!isBrowserEnvironment()) {
		return null;
	}
	const key = buildPickerIntentStorageKey(diagramRequestId);
	let raw: string | null;
	try {
		raw = window.sessionStorage.getItem(key);
	} catch {
		return null;
	}
	if (raw === null) {
		return null;
	}
	// Remove immediately — at-most-once semantics. Even if the JSON.parse
	// below throws or the entry is expired, we still want it gone so a
	// retry doesn't keep re-encountering the broken row.
	try {
		window.sessionStorage.removeItem(key);
	} catch {
		// Best effort; continue with the parse attempt.
	}
	let parsed: PickerIntent;
	try {
		parsed = JSON.parse(raw) as PickerIntent;
	} catch {
		return null;
	}
	// Defensive shape check — guard against future format changes
	// landing alongside stale persisted entries.
	if (
		typeof parsed !== "object" ||
		parsed === null ||
		typeof parsed.createdAt !== "number"
	) {
		return null;
	}
	// 60-second expiry per spec § 11 row 8. The caller fires
	// `diagram_auto_insert_picker_timeout` on the `null` return.
	if (Date.now() - parsed.createdAt > PICKER_INTENT_EXPIRY_MS) {
		return null;
	}
	return parsed;
}

/**
 * Forcefully remove an intent without consuming it. Used by the
 * picker UI's `useEffect` cleanup if the dialog is closed without a
 * row selection (so abandoned intents don't linger in storage).
 *
 * SSR no-op: returns immediately when called outside a browser.
 */
export function expirePickerIntent(diagramRequestId: string): void {
	if (!isBrowserEnvironment()) {
		return;
	}
	try {
		window.sessionStorage.removeItem(
			buildPickerIntentStorageKey(diagramRequestId),
		);
	} catch {
		// Best effort. The 60-second expiry on the read path is the
		// authoritative fallback if removal here silently fails.
	}
}
