-- The ("pullRequestState", "pullRequestNextAttemptAt") index on
-- project_instruction_snapshot (Fizzy #2563 spec §4.1, §9): the proposal
-- pull-request sweeper's due clock, read by its Recover, Restart and Close
-- sub-batches. The explicit name matches the schema's `map:`; Prisma's
-- default would exceed Postgres's 63-character limit (plan R18).
--
-- CONCURRENTLY because project_instruction_snapshot is populated and a plain
-- build takes a write lock on it for the length of the build. NO `IF NOT
-- EXISTS`: a failed concurrent build leaves an invalid index behind under this
-- name, and the clause would then skip the rebuild and record the migration as
-- applied with no index. Recovery per docs/database-promotion.md: find it with
--   SELECT indexrelid::regclass FROM pg_index WHERE NOT indisvalid;
-- then DROP INDEX that name before re-running the migration.
--
-- KEEP THIS MIGRATION TO ONE STATEMENT: CONCURRENTLY cannot run inside the
-- transaction Prisma wraps a multi-statement migration in.
CREATE INDEX CONCURRENTLY "project_instruction_snapshot_pr_due_idx" ON "project_instruction_snapshot"("pullRequestState", "pullRequestNextAttemptAt");
