/**
 * A2A Protocol Server for Task Planner Agent
 *
 * Exposes the LangGraph agent via A2A protocol endpoints so it can be
 * discovered and invoked by the orchestrator agent.
 */

import { serve } from "@hono/node-server";
import type { AgentSkill } from "@repo/agent-core";
import { A2AServer, createLangGraphA2AExecutor } from "@repo/agent-core";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { v4 as uuidv4 } from "uuid";
import { taskPlannerGraph } from "./agent.js";

// Configuration
const PORT = Number.parseInt(process.env.PORT || "8226", 10);
const HOST = process.env.HOST || "0.0.0.0";
const BASE_URL = process.env.BASE_URL || `http://localhost:${PORT}`;

// Define agent skills for A2A discovery
const AGENT_SKILLS: AgentSkill[] = [
	{
		id: "plan-tasks",
		name: "Plan Tasks",
		description:
			"Break down a goal or feature into actionable development tasks with dependencies and risk analysis",
		parameters: {
			type: "object",
			properties: {
				goal: {
					type: "string",
					description: "The goal or feature to break down",
				},
				context: {
					type: "string",
					description:
						"Additional context about the project or requirements",
				},
			},
			required: ["goal"],
		},
		examples: [
			"Break down implementing user authentication",
			"Plan the tasks for adding a payment system",
			"Create a task breakdown for implementing a search feature",
		],
		tags: ["planning", "tasks", "project-management"],
	},
	{
		id: "analyze-risks",
		name: "Analyze Risks",
		description:
			"Identify and assess technical and project risks in a plan",
		examples: [
			"What are the risks in implementing this feature?",
			"Analyze potential blockers for this task",
		],
		tags: ["risk", "analysis", "planning"],
	},
];

// Define types for the task planner result (without messages since graph returns BaseMessage[])
interface TaskPlannerGraphResult {
	document?: string;
	decomposedTasks?: Array<{
		id: string;
		title: string;
		description: string;
		estimate: number;
		dependencies: string[];
		complexity: string;
		riskScore: number;
	}>;
	riskAnalysis?: {
		overallScore: number;
		factors: Array<{
			category: string;
			description: string;
			severity: string;
		}>;
		recommendations: string[];
	};
	executionPlan?: {
		phases: Array<{
			name: string;
			tasks: string[];
			duration: number;
		}>;
		totalDuration: number;
		parallelDuration: number;
	};
	messages: unknown[]; // BaseMessage[] from LangGraph
	error?: string;
}

// Create A2A executor that wraps the LangGraph graph
const a2aExecutor = createLangGraphA2AExecutor(
	async (input: Record<string, unknown>) => {
		const messages = input.messages as Array<{
			role: string;
			content: string;
		}>;
		const lastMessage = messages[messages.length - 1];
		const userMessage = lastMessage?.content || "";
		const projectDescription = input.context as string | undefined;

		console.log("[A2A Server] Invoking Task Planner graph with:", {
			messageLength: userMessage.length,
		});

		const graphResult = await taskPlannerGraph.invoke({
			messages: [{ role: "user", content: userMessage }],
			userStory: userMessage,
			projectDescription,
		});

		// Cast to our result type (messages will be BaseMessage[])
		const result = graphResult as unknown as TaskPlannerGraphResult;

		console.log("[A2A Server] Graph result:", {
			hasDocument: !!result.document,
			taskCount: result.decomposedTasks?.length || 0,
			hasError: !!result.error,
		});

		// The response is the document generated by the graph
		const response = result.document || "";

		// Convert BaseMessage[] to simple message format
		const outputMessages = (result.messages || []).map((msg) => ({
			role:
				typeof msg === "object" && msg !== null && "role" in msg
					? String((msg as Record<string, unknown>).role)
					: "assistant",
			content:
				typeof msg === "object" && msg !== null && "content" in msg
					? String((msg as Record<string, unknown>).content)
					: String(msg),
		}));

		return {
			response,
			messages: outputMessages,
			error: result.error,
			decomposedTasks: result.decomposedTasks,
			riskAnalysis: result.riskAnalysis,
			executionPlan: result.executionPlan,
		};
	},
	{
		responseField: "response",
		outputTransform: (output: Record<string, unknown>) => {
			const response = (output.response as string) || "";
			const decomposedTasks = output.decomposedTasks as
				| TaskPlannerGraphResult["decomposedTasks"]
				| undefined;
			const riskAnalysis = output.riskAnalysis as
				| TaskPlannerGraphResult["riskAnalysis"]
				| undefined;
			const executionPlan = output.executionPlan as
				| TaskPlannerGraphResult["executionPlan"]
				| undefined;

			const artifacts: Array<{
				id: string;
				name: string;
				description: string;
				mimeType: string;
				parts: Array<{ type: "text"; text: string }>;
			}> = [];

			// Add decomposed tasks as artifact
			if (decomposedTasks && decomposedTasks.length > 0) {
				artifacts.push({
					id: uuidv4(),
					name: "decomposed-tasks",
					description:
						"Decomposed tasks with dependencies and risk scores",
					mimeType: "application/json",
					parts: [
						{
							type: "text" as const,
							text: JSON.stringify(decomposedTasks, null, 2),
						},
					],
				});
			}

			// Add risk analysis as artifact
			if (riskAnalysis) {
				artifacts.push({
					id: uuidv4(),
					name: "risk-analysis",
					description:
						"Risk analysis with factors and recommendations",
					mimeType: "application/json",
					parts: [
						{
							type: "text" as const,
							text: JSON.stringify(riskAnalysis, null, 2),
						},
					],
				});
			}

			// Add execution plan as artifact
			if (executionPlan) {
				artifacts.push({
					id: uuidv4(),
					name: "execution-plan",
					description: "Execution plan with phases and durations",
					mimeType: "application/json",
					parts: [
						{
							type: "text" as const,
							text: JSON.stringify(executionPlan, null, 2),
						},
					],
				});
			}

			return {
				response,
				artifacts,
				metadata: {
					error: output.error,
					taskCount: decomposedTasks?.length || 0,
				},
			};
		},
	},
);

// Create A2A server
const a2aServer = new A2AServer(
	{
		name: "task_planner",
		description:
			"Task Planner agent that breaks down goals and features into actionable development tasks with dependencies, estimates, and risk analysis. Best for: project planning, sprint planning, feature breakdown.",
		url: BASE_URL,
		skills: AGENT_SKILLS,
		protocolVersion: "0.3.0",
		supportsStreaming: false,
		tags: ["planning", "tasks", "project-management", "langgraph"],
	},
	a2aExecutor,
);

// Create Hono app with A2A endpoints
const app = new Hono();

// Enable CORS
app.use("*", cors());

// A2A Protocol Endpoints
const handlers = a2aServer.createHandlers();

// GET /.well-known/agent-card.json (v0.3.0)
app.get("/.well-known/agent-card.json", (c) => {
	return c.json(a2aServer.getAgentCard());
});

// GET /.well-known/agent.json (legacy)
app.get("/.well-known/agent.json", (c) => {
	return c.json(a2aServer.getAgentCard());
});

// POST /a2a/send
app.post("/a2a/send", async (c) => {
	try {
		const body = await c.req.json();
		const response = await handlers.sendMessage(body);
		const result = await response.json();
		return c.json(result, response.status as 200);
	} catch (error) {
		console.error("[A2A Server] Error in /a2a/send:", error);
		return c.json(
			{ error: error instanceof Error ? error.message : "Unknown error" },
			500,
		);
	}
});

// POST /a2a/send/stream
app.post("/a2a/send/stream", async (c) => {
	try {
		const body = await c.req.json();
		const response = handlers.sendMessageStream(body);
		return new Response(response.body, {
			status: 200,
			headers: {
				"Content-Type": "text/event-stream",
				"Cache-Control": "no-cache",
				Connection: "keep-alive",
			},
		});
	} catch (error) {
		console.error("[A2A Server] Error in /a2a/send/stream:", error);
		return c.json(
			{ error: error instanceof Error ? error.message : "Unknown error" },
			500,
		);
	}
});

// GET /a2a/tasks/:taskId
app.get("/a2a/tasks/:taskId", (c) => {
	const taskId = c.req.param("taskId");
	const response = handlers.getTask(taskId);
	return new Response(response.body, {
		status: response.status,
		headers: response.headers,
	});
});

// POST /a2a/tasks/:taskId/cancel
app.post("/a2a/tasks/:taskId/cancel", async (c) => {
	const taskId = c.req.param("taskId");
	const response = await handlers.cancelTask(taskId);
	return new Response(response.body, {
		status: response.status,
		headers: response.headers,
	});
});

// GET /health
app.get("/health", (c) => {
	return c.json({
		status: "healthy",
		agent: "task_planner",
		protocol: "a2a",
		version: "0.3.0",
	});
});

// Start the server
console.log(`[A2A Server] Starting Task Planner on ${HOST}:${PORT}`);
console.log(`[A2A Server] Agent Card: ${BASE_URL}/.well-known/agent.json`);
console.log(`[A2A Server] A2A Send: ${BASE_URL}/a2a/send`);
console.log(`[A2A Server] Health: ${BASE_URL}/health`);

serve({
	fetch: app.fetch,
	hostname: HOST,
	port: PORT,
});

export { app };
