const GREETINGS = [
	"Hey {name}! 👋",
	"Good to see you, {name}! 😊",
	"What's up, {name}? 🙌",
	"How's it going, {name}? 🚀",
	"Hiya, {name}! 🌟",
	"Yo {name}! 😎",
	"Welcome, {name}! 🎉",
	"Howdy, {name}! 🤠",
	"Greetings, {name}! 🌈",
	"Salutations, {name}! 🎩",
	"What's new, {name}? 💌",
	"How are you, {name}? 🤗",
	"Ahoy, {name}! ⚓",
	"Bonjour, {name}! 🥖",
	"Hola, {name}! 🌮",
	"Ciao, {name}! 🍕",
	"Namaste, {name}! 🪷",
	"Konnichiwa, {name}! 🎌",
	"Aloha, {name}! 🌺",
	"Hey there, {name}! 💡",
	"Good day, {name}! 🌞",
	"Welcome back, {name}! 🔄",
	"Long time no see, {name}! ⏰",
	"Great to meet you, {name}! 🤝",
	"Pleased to see you, {name}! 😁",
	"Cheers, {name}! 🥂",
	"Happy to chat, {name}! 💬",
	"What's happening, {name}? 🎈",
	"Missed you, {name}! 💛",
	"Glad you're here, {name}! 📍",
	"Smile, {name}! 😄",
	"Lookin' good, {name}! 👍",
	"What's cooking, {name}? 🍳",
	"Stay cool, {name}! ❄️",
	"Keep shining, {name}! 💎",
	"You're a star, {name}! ⭐",
	"Rise and shine, {name}! 🌅",
	"Keep it up, {name}! 💪",
	"Rock on, {name}! 🤘",
];

export function getRandomGreeting(firstName: string): string {
	const template = GREETINGS[Math.floor(Math.random() * GREETINGS.length)];
	return template.replace("{name}", firstName);
}
