import { Permissions as P, type Permission } from "./permissions";

/**
 * Organization-level roles. Source of truth matches `OrganizationMember.role`
 * (Better Auth). Values must be lowercase to match Better Auth conventions.
 */
export type OrgRole = "owner" | "admin" | "member" | "viewer";

export const ORG_ROLES: readonly OrgRole[] = [
	"owner",
	"admin",
	"member",
	"viewer",
] as const;

/**
 * Project-level roles. Source of truth matches the `ProjectMemberRole` enum
 * in Prisma schema (uppercase). The schema enum must be kept in sync with
 * this list — see migration `project_member_roles`.
 */
export type ProjectRole =
	| "OWNER"
	| "PROJECT_ADMIN"
	| "EDITOR"
	| "COMMENTER"
	| "VIEWER";

export const PROJECT_ROLES: readonly ProjectRole[] = [
	"OWNER",
	"PROJECT_ADMIN",
	"EDITOR",
	"COMMENTER",
	"VIEWER",
] as const;

// ---------- Organization role → permissions ----------

const VIEWER_ORG_PERMISSIONS: readonly Permission[] = [
	P.ORG_READ,
	P.ORG_MEMBERS_READ,
	P.ORG_SETTINGS_READ,
	P.ORG_API_KEYS_READ,
	P.ORG_INTEGRATIONS_READ,
	P.ORG_AI_CONFIG_READ,
	P.ORG_RAG_SETTINGS_READ,
	P.ORG_OPENAPI_READ,
	P.ORG_DATA_CONNECTIONS_READ,
	P.PROJECT_READ,
	P.PROJECT_SETTINGS_READ,
	P.PROJECT_MEMBERS_READ,
	P.STORY_READ,
	P.DOCUMENT_READ,
	P.COMMENT_READ,
	P.CONTEXT_READ,
	P.DIAGRAM_READ,
	P.AGENT_READ,
	P.AGENT_TEMPLATE_READ,
	P.AI_MEMORY_READ,
	P.MCP_READ,
	P.PROMPT_READ,
	P.REPORT_READ,
	P.REPORT_TEMPLATE_READ,
	P.SKILL_READ,
	P.INTEGRATION_READ,
	P.WORKSPACE_READ,
	P.DASHBOARD_READ,
	P.USER_READ_SELF,
	P.USER_UPDATE_SELF,
	P.NOTIFICATIONS_READ,
	P.ARCHITECTURE_DECISION_READ,
	P.TEST_CASE_READ,
	P.PUBLISHING_TOPIC_READ,
];

const MEMBER_ORG_PERMISSIONS: readonly Permission[] = [
	...VIEWER_ORG_PERMISSIONS,
	P.PROJECT_CREATE,
	P.PROJECT_UPDATE,
	P.STORY_CREATE,
	P.STORY_UPDATE,
	P.STORY_MOVE,
	P.STORY_TASK_MANAGE,
	P.DOCUMENT_CREATE,
	P.DOCUMENT_UPDATE,
	P.DOCUMENT_LOCK,
	P.COMMENT_CREATE,
	P.COMMENT_UPDATE,
	P.COMMENT_DELETE,
	P.CONTEXT_CREATE,
	P.CONTEXT_UPDATE,
	P.CONTEXT_DELETE,
	P.DIAGRAM_CREATE,
	P.DIAGRAM_UPDATE,
	P.DIAGRAM_DELETE,
	P.AGENT_CREATE,
	P.AGENT_UPDATE,
	P.AGENT_EXECUTE,
	P.AI_CHAT,
	P.AI_MODEL_RESOLVE,
	P.AI_MEMORY_MANAGE,
	P.MCP_CREATE,
	P.MCP_UPDATE,
	P.MCP_CONNECT,
	P.PROMPT_CREATE,
	P.PROMPT_UPDATE,
	P.REPORT_CREATE,
	P.REPORT_UPDATE,
	P.REPORT_EXECUTE,
	P.REPORT_SHARE,
	P.SKILL_CREATE,
	P.SKILL_UPDATE,
	P.INTEGRATION_USE,
	P.WORKSPACE_CREATE,
	P.WORKSPACE_UPDATE,
	P.ARCHITECTURE_DECISION_CREATE,
	P.ARCHITECTURE_DECISION_UPDATE,
	P.TEST_CASE_CREATE,
	P.TEST_CASE_UPDATE,
	P.PUBLISHING_TOPIC_CREATE,
	P.PUBLISHING_TOPIC_UPDATE,
];

const ADMIN_ORG_PERMISSIONS: readonly Permission[] = [
	...MEMBER_ORG_PERMISSIONS,
	P.ORG_UPDATE,
	P.ORG_MEMBERS_INVITE,
	P.ORG_MEMBERS_REMOVE,
	P.ORG_MEMBERS_UPDATE_ROLE,
	P.ORG_SETTINGS_EDIT,
	P.ORG_API_KEYS_CREATE,
	P.ORG_API_KEYS_DELETE,
	P.ORG_AUDIT_LOG_READ,
	P.ORG_AUDIT_LOG_EXPORT,
	P.ORG_INTEGRATIONS_MANAGE,
	P.ORG_AI_CONFIG_EDIT,
	P.ORG_RAG_SETTINGS_EDIT,
	P.ORG_OPENAPI_MANAGE,
	P.ORG_DATA_CONNECTIONS_MANAGE,
	P.ORG_BILLING_READ,
	P.ORG_BILLING_MANAGE,
	P.PROJECT_DELETE,
	P.PROJECT_TRANSFER,
	P.PROJECT_SETTINGS_EDIT,
	P.PROJECT_MEMBERS_MANAGE,
	P.STORY_DELETE,
	P.DOCUMENT_DELETE,
	P.AGENT_DELETE,
	P.AGENT_TEMPLATE_MANAGE,
	P.MCP_DELETE,
	P.PROMPT_DELETE,
	P.REPORT_DELETE,
	P.REPORT_TEMPLATE_MANAGE,
	P.SKILL_DELETE,
	P.INTEGRATION_CONNECT,
	P.INTEGRATION_DISCONNECT,
	P.WORKSPACE_DELETE,
	P.ARCHITECTURE_DECISION_DELETE,
	P.TEST_CASE_DELETE,
	P.PUBLISHING_TOPIC_DELETE,
];

const OWNER_ORG_PERMISSIONS: readonly Permission[] = [
	...ADMIN_ORG_PERMISSIONS,
	P.ORG_DELETE,
];

export const ORG_ROLE_PERMISSIONS: Record<OrgRole, readonly Permission[]> =
	Object.freeze({
		owner: OWNER_ORG_PERMISSIONS,
		admin: ADMIN_ORG_PERMISSIONS,
		member: MEMBER_ORG_PERMISSIONS,
		viewer: VIEWER_ORG_PERMISSIONS,
	});

// ---------- Project role → permissions ----------

const VIEWER_PROJECT_PERMISSIONS: readonly Permission[] = [
	P.PROJECT_READ,
	P.PROJECT_SETTINGS_READ,
	P.PROJECT_MEMBERS_READ,
	P.STORY_READ,
	P.DOCUMENT_READ,
	P.COMMENT_READ,
	P.CONTEXT_READ,
	P.DIAGRAM_READ,
	P.AGENT_READ,
	P.REPORT_READ,
	P.ARCHITECTURE_DECISION_READ,
	P.TEST_CASE_READ,
	P.PUBLISHING_TOPIC_READ,
];

const COMMENTER_PROJECT_PERMISSIONS: readonly Permission[] = [
	...VIEWER_PROJECT_PERMISSIONS,
	P.COMMENT_CREATE,
	P.COMMENT_UPDATE,
];

const EDITOR_PROJECT_PERMISSIONS: readonly Permission[] = [
	...COMMENTER_PROJECT_PERMISSIONS,
	P.PROJECT_UPDATE,
	P.STORY_CREATE,
	P.STORY_UPDATE,
	P.STORY_MOVE,
	P.STORY_TASK_MANAGE,
	P.DOCUMENT_CREATE,
	P.DOCUMENT_UPDATE,
	P.DOCUMENT_LOCK,
	P.CONTEXT_CREATE,
	P.CONTEXT_UPDATE,
	P.DIAGRAM_CREATE,
	P.DIAGRAM_UPDATE,
	P.AI_CHAT,
	P.AI_MODEL_RESOLVE,
	P.AGENT_EXECUTE,
	P.REPORT_EXECUTE,
	P.REPORT_SHARE,
	P.ARCHITECTURE_DECISION_CREATE,
	P.ARCHITECTURE_DECISION_UPDATE,
	P.TEST_CASE_CREATE,
	P.TEST_CASE_UPDATE,
	P.PUBLISHING_TOPIC_CREATE,
	P.PUBLISHING_TOPIC_UPDATE,
];

const PROJECT_ADMIN_PROJECT_PERMISSIONS: readonly Permission[] = [
	...EDITOR_PROJECT_PERMISSIONS,
	P.PROJECT_SETTINGS_EDIT,
	P.PROJECT_MEMBERS_MANAGE,
	P.STORY_DELETE,
	P.DOCUMENT_DELETE,
	P.CONTEXT_DELETE,
	P.DIAGRAM_DELETE,
	P.COMMENT_DELETE,
	P.REPORT_CREATE,
	P.REPORT_UPDATE,
	P.REPORT_DELETE,
	P.ARCHITECTURE_DECISION_DELETE,
	P.TEST_CASE_DELETE,
	P.PUBLISHING_TOPIC_DELETE,
];

const OWNER_PROJECT_PERMISSIONS: readonly Permission[] = [
	...PROJECT_ADMIN_PROJECT_PERMISSIONS,
	P.PROJECT_DELETE,
	P.PROJECT_TRANSFER,
];

export const PROJECT_ROLE_PERMISSIONS: Record<
	ProjectRole,
	readonly Permission[]
> = Object.freeze({
	OWNER: OWNER_PROJECT_PERMISSIONS,
	PROJECT_ADMIN: PROJECT_ADMIN_PROJECT_PERMISSIONS,
	EDITOR: EDITOR_PROJECT_PERMISSIONS,
	COMMENTER: COMMENTER_PROJECT_PERMISSIONS,
	VIEWER: VIEWER_PROJECT_PERMISSIONS,
});
