const CURATED_SYSTEM_MCP_SERVER_KEYS = [
	"github",
	"gitlab",
	// Wizard-default PM tool (DEFAULT_PROJECT_MANAGEMENT_KEYS). Tenants on
	// GitLab's REST fallback have no MCPConfig referencing this row, so
	// omitting it here lets seed-mcp-registry's cleanupNonOfficialServers()
	// delete it — the availablePmTools picker then degrades to key-sentinel
	// ids (issue #2824).
	"gitlab-official",
	"playwright",
	"filesystem",
	"postgres",
	"sqlite",
	"memory",
	"fetch",
	"puppeteer",
	"slack",
	"google-drive",
	"google-maps",
	"notion",
	"brave-search",
	"context7",
	"supabase",
	"firecrawl",
	"fabric-browser-automation",
	"exa-search",
	"cloudflare",
	"stripe",
	"resend",
	"vercel",
	"sentry",
	"neon",
	"turso",
	"upstash",
	"twilio",
	"airtable",
	"asana",
	"todoist",
	"raycast",
	"axiom",
	"browserbase",
	"e2b",
	"obsidian",
	"sequential-thinking",
	"everything",
	"time",
	"fabric",
	"fizzy",
	"azure-devops",
	"atlassian",
	"notion-remote",
	"figma",
	"linear-remote",
	"github-remote",
	"slack-remote",
	"excalidraw",
] as const;

export const CURATED_SYSTEM_MCP_SERVER_KEY_SET: ReadonlySet<string> = new Set(
	CURATED_SYSTEM_MCP_SERVER_KEYS,
);
