/**
 * Seed System Report Templates v3
 *
 * STANDARD REPORT FORMAT:
 * All templates follow a consistent structure for professional, rich reports:
 *
 * 1. HEADER - Title, metadata (date, source, period)
 * 2. EXECUTIVE SUMMARY - AI-generated high-level overview
 * 3. KEY METRICS - Quick stats/highlights (when applicable)
 * 4. MAIN CONTENT - Core analysis sections
 * 5. DETAILED DATA - Tables, raw data (when applicable)
 * 6. FOOTER - Generation info, links, disclaimers
 *
 * Categories:
 * - Video & Audio: YouTube summaries, podcast analysis
 * - Content Analysis: Article summaries, document analysis
 * - Development: GitHub, JIRA, Linear reports
 * - Communication: Slack digests, meeting summaries
 * - Business: QBR, weekly reports
 *
 * Run with: pnpm --filter @repo/database seed:report-templates
 */

import { logger } from "@repo/logs";
import { db } from "./client";

// ============================================
// STANDARD REPORT FORMAT TYPES
// ============================================

interface ReportSection {
	id: string;
	title: string;
	type:
		| "text"
		| "table"
		| "ai-generated"
		| "data"
		| "raw"
		| "metrics"
		| "divider";
	config: Record<string, unknown>;
}

interface AiAgent {
	agentId: string;
	task: string;
	outputVariable: string;
}

// ============================================
// STANDARD SECTION BUILDERS
// ============================================

/**
 * Standard Report Header
 * Includes title, metadata line, and optional description
 */
function headerSection(config: {
	titleTemplate: string;
	subtitleTemplate?: string;
	metadataTemplate?: string;
}): ReportSection {
	let template = `# ${config.titleTemplate}`;
	if (config.subtitleTemplate) {
		template += `\n\n*${config.subtitleTemplate}*`;
	}
	if (config.metadataTemplate) {
		template += `\n\n---\n\n${config.metadataTemplate}`;
	}
	return {
		id: "header",
		title: "Header",
		type: "text",
		config: { template },
	};
}

/**
 * Standard Metadata Block
 * Shows report generation info
 */
function _metadataSection(
	fields: { label: string; value: string }[],
): ReportSection {
	const lines = fields.map((f) => `**${f.label}:** ${f.value}`).join(" · ");
	return {
		id: "metadata",
		title: "Metadata",
		type: "text",
		config: { template: lines },
	};
}

/**
 * Executive Summary Section
 * AI-generated high-level overview
 */
function executiveSummarySection(
	outputVariable = "executive_summary",
): ReportSection {
	return {
		id: "executive-summary",
		title: "Executive Summary",
		type: "ai-generated",
		config: {
			outputVariable,
			wrapperTemplate: "## Executive Summary\n\n{{content}}",
		},
	};
}

/**
 * Key Metrics Section
 * Quick stats displayed prominently
 */
function _keyMetricsSection(outputVariable = "key_metrics"): ReportSection {
	return {
		id: "key-metrics",
		title: "Key Metrics",
		type: "ai-generated",
		config: {
			outputVariable,
			wrapperTemplate: "## Key Metrics\n\n{{content}}",
		},
	};
}

/**
 * Main Analysis Section
 * Core AI-generated content
 */
function analysisSection(
	id: string,
	title: string,
	outputVariable: string,
	options?: { wrapperTemplate?: string },
): ReportSection {
	return {
		id,
		title,
		type: "ai-generated",
		config: {
			outputVariable,
			wrapperTemplate:
				options?.wrapperTemplate ?? `## ${title}\n\n{{content}}`,
		},
	};
}

/**
 * Data Table Section
 * Formatted data display
 */
function tableSection(
	id: string,
	title: string,
	dataSourceId: string,
	options?: { collapsible?: boolean; maxRows?: number },
): ReportSection {
	return {
		id,
		title,
		type: "table",
		config: {
			dataSourceId,
			wrapperTemplate: `## ${title}\n\n{{content}}`,
			...options,
		},
	};
}

/**
 * Section Divider
 */
function _dividerSection(): ReportSection {
	return {
		id: "divider",
		title: "",
		type: "text",
		config: { template: "\n---\n" },
	};
}

/**
 * Standard Footer
 * Report generation info and disclaimers
 */
function footerSection(options?: {
	includeTimestamp?: boolean;
	includeDisclaimer?: boolean;
	customNote?: string;
}): ReportSection {
	let template = "\n---\n\n";
	template += "📊 **Report Generated by Fabric**";

	if (options?.includeTimestamp !== false) {
		template += " · {{generatedAt}}";
	}

	if (options?.customNote) {
		template += `\n\n${options.customNote}`;
	}

	if (options?.includeDisclaimer) {
		template +=
			"\n\n*This report was generated using AI analysis. Please verify critical information.*";
	}

	return {
		id: "footer",
		title: "Footer",
		type: "text",
		config: { template },
	};
}

// ============================================
// STANDARD AI AGENT TASK TEMPLATES
// ============================================

/**
 * Standard analysis task with structured output format
 */
function createAnalysisTask(config: {
	context: string;
	sections: string[];
	outputVariable: string;
	tone?: "professional" | "technical" | "executive";
}): AiAgent {
	const sectionList = config.sections
		.map((s, i) => `${i + 1}. ${s}`)
		.join("\n");
	const toneGuide =
		config.tone === "executive"
			? "Use clear, executive-friendly language. Focus on business impact."
			: config.tone === "technical"
				? "Include technical details where relevant. Be precise."
				: "Balance clarity with appropriate detail.";

	return {
		agentId: "default",
		task: `Analyze the ${config.context} and create a structured report with these sections:

${sectionList}

Format Guidelines:
- Use markdown headers (###) for each section
- Use bullet points for lists
- Highlight key numbers and metrics in **bold**
- ${toneGuide}
- Be concise but comprehensive`,
		outputVariable: config.outputVariable,
	};
}

// ============================================
// MCP SERVER REQUIREMENTS
// ============================================

const MCP_REQUIREMENTS = {
	github: {
		key: "github",
		name: "GitHub",
		description: "Access to GitHub repositories, issues, and PRs",
		required: true,
	},
	atlassian: {
		key: "atlassian",
		name: "Atlassian (JIRA)",
		description: "Access to JIRA projects and sprints",
		required: true,
	},
	linear: {
		key: "linear",
		name: "Linear",
		description: "Access to Linear issues and cycles",
		required: true,
	},
	slack: {
		key: "slack",
		name: "Slack",
		description: "Access to Slack channels and messages",
		required: true,
	},
	notion: {
		key: "notion",
		name: "Notion",
		description: "Access to Notion databases and pages",
		required: true,
	},
	fizzy: {
		key: "fizzy",
		name: "Fizzy",
		description: "Access to Fizzy boards, columns, and cards",
		required: true,
	},
};

function createConnections(
	mcpServers: (typeof MCP_REQUIREMENTS)[keyof typeof MCP_REQUIREMENTS][],
	options?: { workspaces?: boolean },
) {
	return {
		mcpServers: mcpServers.map((s) => ({ ...s })),
		workspaces: options?.workspaces
			? {
					enabled: true,
					description:
						"Optional document context for enhanced analysis",
				}
			: undefined,
	};
}

// ============================================
// SYSTEM TEMPLATES WITH STANDARD FORMAT
// ============================================

export const SYSTEM_TEMPLATES = [
	// ============================================
	// VIDEO & AUDIO TEMPLATES
	// ============================================
	{
		key: "youtube-summary",
		name: "YouTube Video Summary",
		description:
			"Get a concise summary of any YouTube video with key points, main topics, timestamps, and actionable takeaways.",
		heroEmojis: ["🎬", "📝", "✨"],
		templateType: "CUSTOM" as const,
		category: "Video & Audio",
		tags: ["youtube", "video", "summary"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "video-content",
					type: "fabric" as const,
					config: {
						source: "youtube",
						pattern: "summarize",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "YouTube video content",
					sections: [
						"One-line summary (what is this video about)",
						"Key Topics Covered (3-5 main topics with brief descriptions)",
						"Important Points (bullet list of key takeaways)",
						"Notable Quotes or Insights",
						"Who Should Watch This (target audience)",
					],
					outputVariable: "analysis",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "{{title}}",
					subtitleTemplate: "Video Summary Report",
					metadataTemplate:
						"**Source:** YouTube · **Duration:** {{duration}} · **Channel:** {{channelName}}",
				}),
				executiveSummarySection("analysis"),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["videoUrl"],
			properties: {
				videoUrl: {
					type: "string",
					description: "YouTube video URL",
					inputType: "url",
				},
			},
		},
	},
	{
		key: "youtube-wisdom",
		name: "YouTube Extract Wisdom",
		description:
			"Extract key insights, memorable quotes, practical ideas, and actionable wisdom from any YouTube video.",
		heroEmojis: ["💡", "🎓", "📚"],
		templateType: "CUSTOM" as const,
		category: "Video & Audio",
		tags: ["youtube", "wisdom", "insights", "learning"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "video-content",
					type: "fabric" as const,
					config: {
						source: "youtube",
						pattern: "extract_wisdom",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "YouTube video content",
					sections: [
						"Core Message (the main thesis or idea)",
						"Key Ideas (5-10 important concepts explained)",
						"Memorable Quotes (verbatim quotes worth remembering)",
						"Practical Wisdom (actionable advice and tips)",
						"Mental Models or Frameworks (any frameworks presented)",
						"References & Resources (books, people, tools mentioned)",
					],
					outputVariable: "wisdom",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "{{title}}",
					subtitleTemplate: "Wisdom Extraction Report",
					metadataTemplate:
						"**Source:** YouTube · **Channel:** {{channelName}}",
				}),
				analysisSection("wisdom", "Extracted Wisdom", "wisdom"),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["videoUrl"],
			properties: {
				videoUrl: {
					type: "string",
					description: "YouTube video URL",
					inputType: "url",
				},
			},
		},
	},
	{
		key: "youtube-transcript",
		name: "YouTube Transcript",
		description:
			"Get the full transcript of any YouTube video in a clean, readable format with timestamps.",
		heroEmojis: ["📜", "🎬", "📋"],
		templateType: "CUSTOM" as const,
		category: "Video & Audio",
		tags: ["youtube", "transcript", "text"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "transcript",
					type: "fabric" as const,
					config: {
						source: "youtube",
					},
				},
			],
			aiAgents: [],
			sections: [
				headerSection({
					titleTemplate: "{{title}}",
					subtitleTemplate: "Full Transcript",
					metadataTemplate:
						"**Source:** YouTube · **Duration:** {{duration}} · **Channel:** {{channelName}}",
				}),
				{
					id: "description",
					title: "Video Description",
					type: "text",
					config: {
						template: "## Video Description\n\n{{description}}",
					},
				},
				{
					id: "transcript",
					title: "Transcript",
					type: "raw",
					config: {
						dataSourceId: "transcript",
						field: "transcript",
						wrapperTemplate: "## Full Transcript\n\n{{content}}",
					},
				},
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["videoUrl"],
			properties: {
				videoUrl: {
					type: "string",
					description: "YouTube video URL",
					inputType: "url",
				},
			},
		},
	},
	{
		key: "podcast-summary",
		name: "Podcast Episode Summary",
		description:
			"Summarize any podcast episode with main topics, guest insights, key discussions, and takeaways.",
		heroEmojis: ["🎙️", "📻", "📝"],
		templateType: "CUSTOM" as const,
		category: "Video & Audio",
		tags: ["podcast", "audio", "summary"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "podcast-content",
					type: "fabric" as const,
					config: {
						source: "youtube",
						pattern: "summarize",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "podcast episode",
					sections: [
						"Episode Overview (one paragraph summary)",
						"Host & Guest Information (if identifiable)",
						"Main Topics Discussed (with time context if available)",
						"Key Insights from Guests",
						"Memorable Quotes",
						"Actionable Takeaways",
						"Recommended For (who would benefit from this episode)",
					],
					outputVariable: "podcast_analysis",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "{{title}}",
					subtitleTemplate: "Podcast Episode Summary",
					metadataTemplate:
						"**Source:** {{channelName}} · **Duration:** {{duration}}",
				}),
				analysisSection(
					"summary",
					"Episode Summary",
					"podcast_analysis",
				),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["videoUrl"],
			properties: {
				videoUrl: {
					type: "string",
					description: "Podcast episode URL (YouTube)",
					inputType: "url",
				},
			},
		},
	},
	{
		key: "lecture-notes",
		name: "Lecture Notes Generator",
		description:
			"Transform any educational video into structured study notes with key concepts, definitions, and examples.",
		heroEmojis: ["📖", "🎓", "✏️"],
		templateType: "CUSTOM" as const,
		category: "Video & Audio",
		tags: ["education", "lecture", "notes", "study"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "lecture-content",
					type: "fabric" as const,
					config: {
						source: "youtube",
						pattern: "extract_wisdom",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "educational lecture/video",
					sections: [
						"Lecture Overview (subject, level, prerequisites)",
						"Learning Objectives (what you'll learn)",
						"Key Concepts & Definitions (with clear explanations)",
						"Important Formulas or Frameworks",
						"Examples & Case Studies",
						"Common Mistakes to Avoid",
						"Practice Questions (if applicable)",
						"Further Reading & Resources",
					],
					outputVariable: "lecture_notes",
					tone: "technical",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "{{title}}",
					subtitleTemplate: "Study Notes",
					metadataTemplate:
						"**Subject:** {{subject}} · **Instructor:** {{channelName}}",
				}),
				analysisSection("notes", "Lecture Notes", "lecture_notes"),
				footerSection({
					includeTimestamp: true,
					customNote:
						"💡 *Review these notes within 24 hours to maximize retention.*",
				}),
			],
		},
		parameters: {
			required: ["videoUrl"],
			properties: {
				videoUrl: {
					type: "string",
					description: "Lecture/educational video URL",
					inputType: "url",
				},
				subject: {
					type: "string",
					description: "Subject/topic (optional)",
				},
			},
		},
	},

	// ============================================
	// CONTENT ANALYSIS TEMPLATES
	// ============================================
	{
		key: "article-summary",
		name: "Article Summarizer",
		description:
			"Get a comprehensive summary of any article with key arguments, evidence, and main conclusions.",
		heroEmojis: ["📰", "📝", "⚡"],
		templateType: "CUSTOM" as const,
		category: "Content Analysis",
		tags: ["article", "summary", "reading"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "article-content",
					type: "fabric" as const,
					config: {
						pattern: "summarize",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "article content",
					sections: [
						"TL;DR (2-3 sentence summary)",
						"Main Argument or Thesis",
						"Key Points (bullet list)",
						"Supporting Evidence",
						"Author's Conclusions",
						"Critical Assessment (strengths/weaknesses)",
					],
					outputVariable: "article_summary",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "Article Summary",
					subtitleTemplate: "Content Analysis Report",
				}),
				analysisSection("summary", "Summary", "article_summary"),
				footerSection({
					includeTimestamp: true,
					includeDisclaimer: true,
				}),
			],
		},
		parameters: {
			required: ["content"],
			properties: {
				content: {
					type: "string",
					description: "Article text or URL",
					inputType: "textarea",
				},
			},
		},
	},
	{
		key: "content-insights",
		name: "Content Insights Extractor",
		description:
			"Extract actionable insights, key ideas, patterns, and recommendations from any text content.",
		heroEmojis: ["💡", "🔍", "📊"],
		templateType: "CUSTOM" as const,
		category: "Content Analysis",
		tags: ["insights", "analysis", "extraction"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "content-input",
					type: "fabric" as const,
					config: {
						pattern: "extract_wisdom",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "text content",
					sections: [
						"Core Theme or Message",
						"Key Insights (numbered list with explanations)",
						"Patterns & Trends Identified",
						"Actionable Recommendations",
						"Questions Raised",
						"Connections to Other Ideas",
					],
					outputVariable: "content_insights",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "Content Insights Report",
					subtitleTemplate: "Deep Analysis & Extraction",
				}),
				analysisSection("insights", "Key Insights", "content_insights"),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["content"],
			properties: {
				content: {
					type: "string",
					description: "Content to analyze",
					inputType: "textarea",
				},
			},
		},
	},
	{
		key: "meeting-notes",
		name: "Meeting Notes Summarizer",
		description:
			"Transform meeting transcripts into actionable notes with decisions, action items, and follow-ups.",
		heroEmojis: ["📋", "✅", "👥"],
		templateType: "CUSTOM" as const,
		category: "Content Analysis",
		tags: ["meeting", "notes", "action-items"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "meeting-content",
					type: "fabric" as const,
					config: {
						pattern: "summarize_meeting",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "meeting transcript or notes",
					sections: [
						"Meeting Overview (purpose, attendees, duration)",
						"Key Discussion Points",
						"Decisions Made (with rationale)",
						"Action Items (owner, deadline, description)",
						"Open Questions & Parking Lot Items",
						"Next Steps & Follow-up Schedule",
					],
					outputVariable: "meeting_summary",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "{{meetingTitle}}",
					subtitleTemplate: "Meeting Notes",
					metadataTemplate:
						"**Date:** {{meetingDate}} · **Attendees:** {{attendees}}",
				}),
				analysisSection(
					"summary",
					"Meeting Summary",
					"meeting_summary",
				),
				footerSection({
					includeTimestamp: true,
					customNote:
						"📌 *Please confirm action items with your name and update status in your project tracker.*",
				}),
			],
		},
		parameters: {
			required: ["content"],
			properties: {
				content: {
					type: "string",
					description: "Meeting transcript or notes",
					inputType: "textarea",
				},
				meetingTitle: {
					type: "string",
					description: "Meeting title",
					default: "Team Meeting",
				},
				meetingDate: {
					type: "string",
					description: "Meeting date",
					default: "{{TODAY}}",
				},
				attendees: {
					type: "string",
					description: "List of attendees",
				},
			},
		},
	},
	{
		key: "claims-analysis",
		name: "Claims & Arguments Analyzer",
		description:
			"Critically analyze claims and arguments with evidence assessment, logical fallacy detection, and credibility rating.",
		heroEmojis: ["🔬", "⚖️", "🧠"],
		templateType: "CUSTOM" as const,
		category: "Content Analysis",
		tags: ["analysis", "claims", "critical-thinking"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "claims-content",
					type: "fabric" as const,
					config: {
						pattern: "analyze_claims",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "content claims and arguments",
					sections: [
						"Main Claims Identified (numbered list)",
						"Evidence Assessment (for each claim: strong/moderate/weak/none)",
						"Logical Fallacies Detected (if any)",
						"Source Credibility Analysis",
						"Counter-Arguments to Consider",
						"Overall Credibility Score (1-10 with justification)",
						"Recommendations for Further Verification",
					],
					outputVariable: "claims_analysis",
					tone: "technical",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "Claims Analysis Report",
					subtitleTemplate: "Critical Evaluation",
				}),
				analysisSection(
					"analysis",
					"Claims Analysis",
					"claims_analysis",
				),
				footerSection({
					includeTimestamp: true,
					includeDisclaimer: true,
				}),
			],
		},
		parameters: {
			required: ["content"],
			properties: {
				content: {
					type: "string",
					description: "Content to analyze for claims",
					inputType: "textarea",
				},
			},
		},
	},
	{
		key: "content-rating",
		name: "Content Quality Rater",
		description:
			"Evaluate content quality across multiple dimensions with scores, detailed breakdown, and improvement suggestions.",
		heroEmojis: ["⭐", "📊", "🎯"],
		templateType: "CUSTOM" as const,
		category: "Content Analysis",
		tags: ["rating", "quality", "evaluation"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [
				{
					id: "rating-content",
					type: "fabric" as const,
					config: {
						pattern: "rate_content",
					},
				},
			],
			aiAgents: [
				createAnalysisTask({
					context: "content quality",
					sections: [
						"Overall Score (X/10) with one-line verdict",
						"Dimension Scores (each X/10):\n   - Clarity & Readability\n   - Depth & Substance\n   - Accuracy & Reliability\n   - Originality & Value\n   - Structure & Organization",
						"Strengths (what works well)",
						"Areas for Improvement",
						"Specific Suggestions (actionable recommendations)",
						"Comparison to Similar Content",
					],
					outputVariable: "content_rating",
					tone: "professional",
				}),
			],
			sections: [
				headerSection({
					titleTemplate: "Content Quality Report",
					subtitleTemplate: "Comprehensive Evaluation",
				}),
				analysisSection(
					"rating",
					"Quality Assessment",
					"content_rating",
				),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["content"],
			properties: {
				content: {
					type: "string",
					description: "Content to rate",
					inputType: "textarea",
				},
			},
		},
	},

	// ============================================
	// DEVELOPMENT TEMPLATES
	// ============================================
	{
		key: "github-issues-weekly",
		name: "GitHub Issues Weekly Summary",
		description:
			"Comprehensive weekly GitHub issues report with trends, team breakdown, blockers, and recommendations.",
		heroEmojis: ["🐙", "📊", "📋"],
		templateType: "SPRINT_COMPLETION" as const,
		category: "Development",
		tags: ["github", "issues", "weekly"],
		outputFormat: "MARKDOWN" as const,
		connections: {
			// GitHub works with both MCP and Integration - prefer integration for simpler setup
			integrations: [
				{
					key: "github",
					name: "GitHub",
					description:
						"Access to GitHub repositories, issues, and PRs",
					required: true,
				},
			],
			mcpServers: [], // Can also use MCP if configured
			workspaces: {
				enabled: true,
				description: "Optional document context for enhanced analysis",
			},
		},
		definition: {
			dataSources: [
				{
					id: "github-issues",
					type: "integration" as const, // Use integration handler
					provider: "github",
					operation: "list_issues",
					config: {
						limit: 100,
						fetchMode: "date_range", // Fetch issues within the report period
					},
				},
			],
			aiAgents: [
				{
					agentId: "default",
					task: `Analyze the GitHub issues data and create a comprehensive weekly report with these sections:

### Executive Summary
2-3 sentences on overall issue health and key highlights.

### Key Metrics
- Total Issues: X (opened: Y, closed: Z)
- Resolution Rate: X%
- Average Time to Close: X days
- Most Active Contributors: list top 3

### Issues by Category
Group by labels/type with counts and trends.

### Blockers & At-Risk Issues
- Issues marked as blocked or stale (no activity >7 days)
- High-priority items needing attention

### Team Breakdown
Activity by assignee with opened/closed counts.

### Trends & Patterns
Week-over-week comparison and notable patterns.

### Recommendations
3-5 actionable suggestions for improvement.

Use tables where appropriate. Highlight critical items in **bold**.`,
					outputVariable: "analysis",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "{{repo}} Issues Report",
					subtitleTemplate: "Weekly Summary",
					metadataTemplate:
						"**Repository:** {{owner}}/{{repo}} · **Period:** {{weekStart}} - {{weekEnd}}",
				}),
				analysisSection("summary", "Analysis", "analysis"),
				tableSection("issues-table", "All Issues", "github-issues", {
					collapsible: true,
					maxRows: 50,
				}),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["owner", "repo"],
			properties: {
				owner: { type: "string", description: "Repository owner" },
				repo: { type: "string", description: "Repository name" },
				weekStart: {
					type: "string",
					description: "Week start date",
					default: "{{WEEK_START}}",
				},
				weekEnd: {
					type: "string",
					description: "Week end date",
					default: "{{TODAY}}",
				},
			},
		},
	},
	{
		key: "github-pr-status",
		name: "GitHub PR Review Status",
		description:
			"Detailed pull request analysis with review turnaround times, approval rates, and code quality insights.",
		heroEmojis: ["🔀", "👀", "✅"],
		templateType: "SPRINT_COMPLETION" as const,
		category: "Development",
		tags: ["github", "pull-requests", "code-review"],
		outputFormat: "MARKDOWN" as const,
		connections: createConnections([MCP_REQUIREMENTS.github]),
		definition: {
			dataSources: [
				{
					id: "github-prs",
					type: "mcp" as const,
					config: {
						toolName: "list_pull_requests",
						mcpServerKey: "github",
						args: { state: "all", per_page: 50 },
					},
				},
			],
			aiAgents: [
				{
					agentId: "default",
					task: `Analyze the pull request data and create a comprehensive review status report:

### Executive Summary
Overall PR health, review velocity, and key highlights.

### Key Metrics
| Metric | Value | Trend |
|--------|-------|-------|
| Open PRs | X | ↑/↓ |
| Merged This Week | X | ↑/↓ |
| Avg Review Time | X hours | ↑/↓ |
| First Review Time | X hours | - |

### PRs Needing Attention
- Stale PRs (open >7 days without review)
- PRs with requested changes
- Large PRs (>500 lines) requiring extra review

### Review Leaderboard
Top reviewers with review counts and average turnaround.

### Merged PRs Summary
Brief description of major changes merged.

### Recommendations
Suggestions for improving review process.`,
					outputVariable: "pr_analysis",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "{{repo}} PR Status",
					subtitleTemplate: "Code Review Report",
					metadataTemplate:
						"**Repository:** {{owner}}/{{repo}} · **Generated:** {{TODAY}}",
				}),
				analysisSection("summary", "PR Analysis", "pr_analysis"),
				tableSection("prs-table", "Pull Requests", "github-prs", {
					collapsible: true,
				}),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["owner", "repo"],
			properties: {
				owner: { type: "string", description: "Repository owner" },
				repo: { type: "string", description: "Repository name" },
			},
		},
	},
	{
		key: "jira-sprint-report",
		name: "JIRA Sprint Report",
		description:
			"Sprint completion report with velocity analysis, burndown insights, team performance, and retrospective summary.",
		heroEmojis: ["🏃", "📈", "🎯"],
		templateType: "SPRINT_COMPLETION" as const,
		category: "Development",
		tags: ["jira", "sprint", "agile"],
		outputFormat: "MARKDOWN" as const,
		connections: createConnections([MCP_REQUIREMENTS.atlassian]),
		definition: {
			dataSources: [
				{
					id: "sprint-issues",
					type: "mcp" as const,
					config: {
						toolName: "jira_get_sprint_issues",
						mcpServerKey: "atlassian",
						args: {},
					},
				},
			],
			aiAgents: [
				{
					agentId: "default",
					task: `Create a comprehensive sprint report with these sections:

### Sprint Overview
| Metric | Value |
|--------|-------|
| Sprint Goal | [from data or param] |
| Duration | X days |
| Team Size | X members |

### Sprint Goal Achievement
Was the goal met? Explain with evidence.

### Velocity & Completion
- Committed: X story points
- Completed: Y story points
- Completion Rate: Z%
- Velocity vs Last Sprint: ↑/↓ X%

### Work Breakdown
| Status | Stories | Points |
|--------|---------|--------|
| Done | X | Y |
| In Progress | X | Y |
| Carried Over | X | Y |

### Team Performance
Individual contributions and observations.

### Blockers & Impediments
Issues that slowed progress.

### Retrospective Insights
- What went well
- What could improve
- Action items for next sprint

### Next Sprint Recommendations
Suggestions for upcoming sprint planning.`,
					outputVariable: "sprint_analysis",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "Sprint: {{sprintName}}",
					subtitleTemplate: "Sprint Completion Report",
					metadataTemplate:
						"**Team:** {{teamName}} · **Sprint:** {{sprintId}}",
				}),
				analysisSection("report", "Sprint Report", "sprint_analysis"),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["sprintId"],
			properties: {
				sprintId: { type: "string", description: "Sprint ID" },
				sprintName: { type: "string", description: "Sprint name" },
				teamName: { type: "string", description: "Team name" },
			},
		},
	},
	{
		key: "linear-cycle-report",
		name: "Linear Cycle Report",
		description:
			"Cycle completion report with throughput analysis, workload distribution, and planning insights.",
		heroEmojis: ["🔄", "📐", "⚡"],
		templateType: "SPRINT_COMPLETION" as const,
		category: "Development",
		tags: ["linear", "cycle", "agile"],
		outputFormat: "MARKDOWN" as const,
		connections: createConnections([MCP_REQUIREMENTS.linear], {
			workspaces: true,
		}),
		definition: {
			dataSources: [
				{
					id: "cycle-issues",
					type: "mcp" as const,
					config: {
						toolName: "linear_search_issues",
						mcpServerKey: "linear",
						args: {},
					},
				},
			],
			aiAgents: [
				{
					agentId: "default",
					task: `Create a Linear cycle completion report:

### Cycle Summary
Brief overview of the cycle's goals and outcomes.

### Key Metrics
| Metric | Value | vs Last Cycle |
|--------|-------|---------------|
| Total Issues | X | ↑/↓ |
| Completed | Y | ↑/↓ |
| Completion Rate | Z% | ↑/↓ |
| Avg Cycle Time | X days | ↑/↓ |

### Issues by Status
Breakdown of all issues by current status.

### Issues by Priority
- Urgent: X
- High: Y
- Medium: Z
- Low: W

### Team Workload
Who worked on what, balanced view.

### Blockers & Risks
Issues that are blocked or at risk.

### Carried Over Items
What's moving to next cycle and why.

### Next Cycle Planning
Recommendations for capacity and priorities.`,
					outputVariable: "cycle_analysis",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "Cycle Report",
					subtitleTemplate: "Cycle Completion Analysis",
					metadataTemplate:
						"**Cycle:** {{cycleId}} · **Team:** {{teamName}}",
				}),
				analysisSection("report", "Cycle Analysis", "cycle_analysis"),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: [],
			properties: {
				cycleId: { type: "string", description: "Cycle ID (optional)" },
				teamName: { type: "string", description: "Team name" },
			},
		},
	},

	// ============================================
	// COMMUNICATION TEMPLATES
	// ============================================
	{
		key: "slack-weekly-digest",
		name: "Slack Weekly Digest",
		description:
			"Weekly digest of Slack channel activity with key discussions, decisions, action items, and team highlights.",
		heroEmojis: ["💬", "📊", "🗓️"],
		templateType: "MONTHLY_REPORT" as const,
		category: "Communication",
		tags: ["slack", "digest", "weekly"],
		outputFormat: "MARKDOWN" as const,
		connections: {
			// Use integration for Slack (OAuth-based, simpler setup than MCP)
			integrations: [
				{
					key: "slack",
					name: "Slack",
					description: "Access to Slack channels and messages",
					required: true,
					requiredScopes: ["channels:history", "groups:history"],
				},
			],
			mcpServers: [], // Not needed for this template
			workspaces: { enabled: false },
		},
		definition: {
			dataSources: [
				{
					id: "slack-messages",
					type: "integration" as const, // Use integration handler, not MCP
					provider: "slack",
					operation: "get_channel_history",
					config: {
						limit: 1000, // Fetch more messages for comprehensive analysis
						fetchMode: "incremental", // Support incremental for scheduled runs
					},
					// Enable RAG for large message volumes
					processing: {
						chunkSize: 500,
						chunkOverlap: 50,
						embedForRag: true,
						summarizeChunks: false,
					},
				},
			],
			aiAgents: [
				{
					agentId: "default",
					task: `Analyze the Slack channel messages and create a comprehensive weekly digest. Structure your response with these sections:

### Executive Summary
2-3 sentence summary of channel activity and key themes.

### Activity Metrics
Present the following metrics in a clear format:
- **Total Messages:** [count]
- **Unique Contributors:** [count]
- **Threads Created:** [count]
- **Reactions Given:** [count]

### Key Discussions
Top 3-5 major topics discussed with brief summaries (2-3 sentences each).

### Decisions Made
Important decisions with context, stakeholders involved, and outcomes.

### Action Items
| Item | Owner | Due Date | Priority | Status |
|------|-------|----------|----------|--------|
Include any tasks, follow-ups, or commitments mentioned.

### Announcements & Updates
Notable announcements, news, or updates shared this week.

### Team Highlights
Shoutouts, achievements, celebrations, or recognition.

### Trending Topics
List of most frequently mentioned topics/keywords.

### Open Questions
Unresolved questions or discussions that need follow-up.

### Contributor Leaderboard
| Contributor | Messages | Threads Started |
|-------------|----------|-----------------|
Top 5 most active contributors.

If no Slack message data is provided, explain clearly what data is missing and what was expected.`,
					outputVariable: "slack_digest",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "#{{channelName}} Weekly Digest",
					subtitleTemplate: "Channel Activity Summary",
					metadataTemplate:
						"**Period:** {{weekDate}} · **Channel ID:** {{channelId}}",
				}),
				// Main digest content
				analysisSection("digest", "Weekly Digest", "slack_digest"),
				footerSection({
					includeTimestamp: true,
					customNote: "📊 *Generated by Fabric Reports*",
				}),
			],
		},
		parameters: {
			required: ["channelId"],
			properties: {
				channelId: { type: "string", description: "Slack channel ID" },
				channelName: { type: "string", description: "Channel name" },
				weekDate: {
					type: "string",
					description: "Week start date",
					default: "{{WEEK_START}}",
				},
			},
		},
	},

	// ============================================
	// BUSINESS TEMPLATES
	// ============================================
	{
		key: "weekly-engineering-report",
		name: "Weekly Engineering Report",
		description:
			"Comprehensive weekly engineering report with code activity, deployments, team velocity, and technical highlights.",
		heroEmojis: ["🛠️", "📊", "🚀"],
		templateType: "MONTHLY_REPORT" as const,
		category: "Business",
		tags: ["engineering", "weekly", "report"],
		outputFormat: "MARKDOWN" as const,
		connections: createConnections([MCP_REQUIREMENTS.github], {
			workspaces: true,
		}),
		definition: {
			dataSources: [
				{
					id: "commits",
					type: "mcp" as const,
					config: {
						toolName: "list_commits",
						mcpServerKey: "github",
						args: { per_page: 100 },
					},
				},
				{
					id: "prs",
					type: "mcp" as const,
					config: {
						toolName: "list_pull_requests",
						mcpServerKey: "github",
						args: { state: "all", per_page: 50 },
					},
				},
			],
			aiAgents: [
				{
					agentId: "default",
					task: `Create a comprehensive weekly engineering report:

### Executive Summary
3-4 sentences on engineering progress, highlights, and focus areas.

### Key Metrics Dashboard
| Metric | This Week | Last Week | Change |
|--------|-----------|-----------|--------|
| Commits | X | Y | ↑/↓ Z% |
| PRs Merged | X | Y | ↑/↓ Z% |
| Issues Closed | X | Y | ↑/↓ Z% |
| Contributors Active | X | Y | - |

### Features Shipped
Major features or improvements released.

### Bug Fixes
Notable bugs fixed with impact assessment.

### Technical Debt Addressed
Refactoring, performance improvements, or cleanup.

### Work in Progress
Major items still in development.

### Team Highlights
Individual contributions and achievements.

### Blockers & Risks
Current blockers and potential risks.

### Next Week Focus
Planned priorities and goals.`,
					outputVariable: "engineering_report",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "Engineering Weekly Report",
					subtitleTemplate: "{{owner}}/{{repo}}",
					metadataTemplate:
						"**Week of:** {{weekDate}} · **Team Lead:** {{teamLead}}",
				}),
				analysisSection(
					"report",
					"Engineering Report",
					"engineering_report",
				),
				footerSection({ includeTimestamp: true }),
			],
		},
		parameters: {
			required: ["owner", "repo"],
			properties: {
				owner: { type: "string", description: "Repository owner" },
				repo: { type: "string", description: "Repository name" },
				weekDate: {
					type: "string",
					description: "Week start date",
					default: "{{WEEK_START}}",
				},
				teamLead: { type: "string", description: "Team lead name" },
			},
		},
	},
	{
		key: "quarterly-review",
		name: "Quarterly Business Review",
		description:
			"Executive-ready quarterly review with achievements, metrics, challenges, and next quarter goals.",
		heroEmojis: ["📈", "🎯", "💼"],
		templateType: "QUARTERLY_REPORT" as const,
		category: "Business",
		tags: ["quarterly", "review", "executive"],
		outputFormat: "MARKDOWN" as const,
		definition: {
			dataSources: [],
			aiAgents: [
				{
					agentId: "default",
					task: `Create an executive-ready Quarterly Business Review structure:

### Executive Summary
2-3 paragraph overview of the quarter.

### Q{{quarter}} Highlights
Top 3-5 achievements with impact metrics.

### Key Performance Indicators
| KPI | Target | Actual | Status |
|-----|--------|--------|--------|
| [Add KPIs] | X | Y | 🟢/🟡/🔴 |

### Project Delivery
Major projects completed or in progress with status.

### Team Updates
Hiring, departures, team structure changes.

### Challenges & Learnings
Key challenges faced and lessons learned.

### Customer/Stakeholder Feedback
Notable feedback and NPS/satisfaction metrics.

### Budget & Resources
Budget utilization and resource allocation.

### Q{{nextQuarter}} Goals
Top priorities and OKRs for next quarter.

### Strategic Initiatives
Long-term initiatives and progress.

### Appendix
Supporting data and detailed metrics.`,
					outputVariable: "qbr_structure",
				},
			],
			sections: [
				headerSection({
					titleTemplate: "Q{{quarter}} {{year}} Business Review",
					subtitleTemplate: "Quarterly Performance Report",
					metadataTemplate:
						"**Department:** {{department}} · **Presenter:** {{presenter}}",
				}),
				analysisSection("review", "Quarterly Review", "qbr_structure"),
				footerSection({
					includeTimestamp: true,
					customNote:
						"📊 *For detailed metrics and supporting data, see the attached appendix.*",
				}),
			],
		},
		parameters: {
			required: ["quarter", "year"],
			properties: {
				quarter: { type: "string", description: "Quarter (1-4)" },
				year: { type: "string", description: "Year" },
				department: { type: "string", description: "Department name" },
				presenter: { type: "string", description: "Presenter name" },
			},
		},
	},
	// ============================================
	// TASK BOARD TEMPLATES
	// ============================================
	{
		key: "task-board-project-report",
		name: "Fizzy Board Report",
		description:
			"Visual project status report from your Fizzy board — status dashboard, velocity analysis, team workload, risk heatmap, and next-sprint recommendations.",
		heroEmojis: ["📋", "📊", "🎯"],
		templateType: "FEATURE_SUMMARY" as const,
		category: "Development",
		tags: [
			"fizzy",
			"task-board",
			"project-report",
			"agile",
			"status",
			"visual",
		],
		outputFormat: "HTML" as const,
		connections: createConnections([MCP_REQUIREMENTS.fizzy], {
			workspaces: true,
		}),
		definition: {
			dataSources: [
				{
					id: "task-board",
					type: "mcp" as const,
					provider: "fizzy",
				},
			] as any[],
			aiAgents: [
				{
					agentId: "default",
					task: `You are generating a visual HTML project report from Fizzy task board data.

## Reading the Gathered Data

The board data has already been collected for you — boards, board details, columns, users and cards. Interpret it as follows:

1. Card data comes from paginated \`fizzy_get_cards\` listings, normalized to a bare card array; the pagination metadata lives under \`_coverage.fizzy_get_cards\` as \`{total_count, pages_fetched, has_more_at_last_page}\`.
2. **The true filtered total is \`_coverage\`'s \`total_count\` — cite that as the board total, never the number of cards you can see.**
3. **When \`has_more_at_last_page\` is true or a page cap was hit, the cards present are a SAMPLE of \`total_count\`: say so plainly in the report and qualify every count derived from them. If \`_board_fix.partial\` is true, coverage is unknown — report totals as partial/unknown rather than citing a stale \`total_count\`.**
4. Closed/archived, stalled and golden cards come from \`indexed_by\` listings scoped to the same board — they are subsets of that board, not separate data sets.
5. The API cannot filter by status or by due date (\`status\`, \`due_before\` and \`due_after\` are NOT supported), so derive status groupings and overdue/upcoming buckets from the card fields in the data (column, closed, due_on, last_active_at).

## Analysis Requirements

From the gathered data, compute:
1. **Status counts**: items by status (to do, in progress, in review, done, blocked)
2. **Type breakdown**: features vs bugs vs tasks vs chores
3. **Priority distribution**: critical/high/medium/low counts
4. **Team workload**: items per assignee, WIP per person, blocked items per person
5. **Velocity indicators**: completed items in current vs previous period (if data available)
6. **Risk signals**: blocked items with age, stale items (no update >7 days), unassigned high-priority items
7. **Highlights**: recently completed notable items, fastest completions
8. **Recommendations**: 3-5 actionable suggestions based on the data patterns

## Output Format

Generate a complete, self-contained HTML page following the "Task Board Visual Report" skill instructions.
The HTML must be production-quality: responsive, accessible, light-only self-contained theme (no @media (prefers-color-scheme: dark) block; declare <meta name="color-scheme" content="light"> and color-scheme: light), CSS-only charts, no external dependencies.

IMPORTANT: The output must be a complete HTML document starting with <!DOCTYPE html>. Do not wrap in markdown code fences. Do not include any text before or after the HTML.`,
					outputVariable: "html_report",
				},
			],
			sections: [
				{
					id: "visual-report",
					title: "",
					type: "ai-generated" as const,
					config: {
						outputVariable: "html_report",
						wrapperTemplate: "{{content}}",
					},
				},
			],
		},
		parameters: {
			required: ["projectName"],
			properties: {
				projectName: {
					type: "string",
					description: "Project or team name for the report title",
				},
				reportPeriod: {
					type: "string",
					description:
						"Time period to cover (e.g., 'Sprint 42', 'Last 2 weeks', 'March 2026')",
					default: "Current Sprint",
				},
				iterationPath: {
					type: "string",
					description:
						"Iteration/sprint path to filter by (Azure DevOps) — e.g., 'MyProject\\\\Sprint 42'",
				},
				teamId: {
					type: "string",
					description:
						"Team ID or name to filter by (provider-specific)",
				},
				includeSubtasks: {
					type: "boolean",
					description: "Include child/sub-task items in the report",
					default: true,
				},
			},
		},
		fabricConfig: {
			strategy: "structured_analysis",
			context: "technical_writer",
			pattern: null,
		},
		skillSlugs: ["task-board-visual-report", "visual-project-recap"],
	},
];

// ============================================
// SKILL ATTACHMENT HELPERS
// ============================================

interface TemplateWithSkills {
	key: string;
	name: string;
	skillSlugs?: string[];
}

async function attachSkillsToTemplate(
	templateId: string,
	template: TemplateWithSkills,
) {
	if (!template.skillSlugs?.length) {
		return;
	}

	for (let i = 0; i < template.skillSlugs.length; i++) {
		const slug = template.skillSlugs[i];
		const skill = await db.skill.findFirst({
			where: { slug, scope: "SYSTEM" },
		});
		if (!skill) {
			const isRequired = i === 0;
			if (isRequired) {
				throw new Error(
					`Required skill "${slug}" not found for template "${template.name}". Run seed:skills first.`,
				);
			}
			logger.warn(
				`  ⚠ Optional skill "${slug}" not found, skipping attachment`,
			);
			continue;
		}

		const existing = await db.reportTemplateSkill.findUnique({
			where: { templateId_skillId: { templateId, skillId: skill.id } },
		});

		if (!existing) {
			await db.reportTemplateSkill.create({
				data: {
					templateId,
					skillId: skill.id,
					sortOrder: i,
					isRequired: i === 0,
				},
			});
			logger.info(`    🔗 Attached skill: ${skill.name}`);
		}
	}
}

// ============================================
// SEED FUNCTION
// ============================================

async function seedReportTemplates() {
	logger.info(
		"\nSeeding System Report Templates v3 (Standardized Format)...",
	);

	let created = 0;
	let updated = 0;

	for (const template of SYSTEM_TEMPLATES) {
		const existing = await db.reportTemplate.findFirst({
			where: {
				OR: [{ name: template.name, scope: "SYSTEM" }],
			},
		});

		const data = {
			name: template.name,
			description: template.description,
			heroEmojis: template.heroEmojis,
			templateType: template.templateType,
			category: template.category,
			tags: template.tags,
			outputFormat: template.outputFormat,
			definition: template.definition as any,
			parameters: template.parameters as any,
			connections: (template as any).connections as any,
			evidenceConfig: (template as any).evidenceConfig as any,
			scope: "SYSTEM" as const,
			isPublic: true,
		};

		let templateId: string;

		if (existing) {
			await db.reportTemplate.update({
				where: { id: existing.id },
				data,
			});
			templateId = existing.id;
			updated++;
			logger.info(`  ✓ Updated: ${template.name}`);
		} else {
			const created_record = await db.reportTemplate.create({
				data,
			});
			templateId = created_record.id;
			created++;
			logger.info(`  + Created: ${template.name}`);
		}

		// Attach skills if defined
		await attachSkillsToTemplate(
			templateId,
			template as TemplateWithSkills,
		);
	}

	logger.success(
		`\n✅ Report Templates - Created: ${created}, Updated: ${updated}`,
	);
	logger.info(`   Total templates: ${SYSTEM_TEMPLATES.length}`);
}

async function main() {
	try {
		await seedReportTemplates();
		logger.success("\n🎉 Report template seeding completed!");
	} catch (error) {
		logger.error("Error seeding report templates:", error);
		process.exit(1);
	} finally {
		await db.$disconnect();
	}
}

// Run if called directly (import-safe for unit tests that read the exported data).
if (require.main === module) {
	main();
}
