import {
	CloudIcon,
	Globe2Icon,
	PackageIcon,
	ShoppingCartIcon,
	SmartphoneIcon,
	ZapIcon,
} from "lucide-react";

export const PROJECT_TYPES = [
	{
		value: "web",
		label: "Web Application",
		description: "Full-stack web application",
		icon: Globe2Icon,
		color: "text-blue-600 dark:text-blue-400",
		bgColor: "bg-blue-100 dark:bg-blue-900/20",
	},
	{
		value: "mobile",
		label: "Mobile App",
		description: "iOS or Android application",
		icon: SmartphoneIcon,
		color: "text-purple-600 dark:text-purple-400",
		bgColor: "bg-purple-100 dark:bg-purple-900/20",
	},
	{
		value: "api",
		label: "API/Backend",
		description: "RESTful or GraphQL API",
		icon: ZapIcon,
		color: "text-yellow-600 dark:text-yellow-400",
		bgColor: "bg-yellow-100 dark:bg-yellow-900/20",
	},
	{
		value: "saas",
		label: "SaaS Platform",
		description: "Software as a Service",
		icon: CloudIcon,
		color: "text-cyan-600 dark:text-cyan-400",
		bgColor: "bg-cyan-100 dark:bg-cyan-900/20",
	},
	{
		value: "ecommerce",
		label: "E-commerce",
		description: "Online store or marketplace",
		icon: ShoppingCartIcon,
		color: "text-green-600 dark:text-green-400",
		bgColor: "bg-green-100 dark:bg-green-900/20",
	},
	{
		value: "other",
		label: "Other",
		description: "Other project type",
		icon: PackageIcon,
		color: "text-gray-600 dark:text-gray-400",
		bgColor: "bg-gray-100 dark:bg-gray-900/20",
	},
];

export const TECH_CATEGORIES: Record<string, string[]> = {
	"Frontend Frameworks": [
		"React",
		"Next.js",
		"Vue.js",
		"Angular",
		"Svelte",
		"SvelteKit",
		"Nuxt.js",
		"Remix",
		"Gatsby",
		"Astro",
		"Solid.js",
		"Qwik",
		"Alpine.js",
		"Lit",
		"Stencil",
		"HTML/CSS/JS",
	],
	"Backend Frameworks": [
		"Node.js",
		"Express.js",
		"Fastify",
		"Koa.js",
		"NestJS",
		"Django",
		"FastAPI",
		"Flask",
		"Ruby on Rails",
		"Sinatra",
		"Laravel",
		"Symfony",
		"CodeIgniter",
		"Spring Boot",
		"ASP.NET Core",
		"Phoenix",
		"Gin",
		"Echo",
		"Fiber",
	],
	"Programming Languages": [
		"JavaScript",
		"TypeScript",
		"Python",
		"Java",
		"C#",
		"Go",
		"Rust",
		"PHP",
		"Ruby",
		"Swift",
		"Kotlin",
		"Dart",
		"Elixir",
		"Scala",
		"C++",
	],
	Databases: [
		"PostgreSQL",
		"MySQL",
		"MongoDB",
		"Redis",
		"SQLite",
		"Supabase",
		"Firebase",
		"DynamoDB",
		"Cassandra",
		"Elasticsearch",
		"MariaDB",
		"CouchDB",
		"Neo4j",
		"Oracle",
		"Cosmos DB",
	],
	"CSS Frameworks": [
		"Tailwind CSS",
		"Bootstrap",
		"Material-UI",
		"Chakra UI",
		"shadcn/ui",
		"Ant Design",
		"Bulma",
		"Foundation",
		"Sass",
		"Less",
		"Styled Components",
		"Emotion",
		"CSS Modules",
	],
	"Mobile Development": [
		"React Native",
		"Flutter",
		"Swift",
		"Kotlin",
		"Expo",
		"Ionic",
		"Xamarin",
		"SwiftUI",
		"Jetpack Compose",
		"Capacitor",
		"NativeScript",
	],
	"Cloud & DevOps": [
		"AWS",
		"Google Cloud",
		"Azure",
		"Vercel",
		"Netlify",
		"Railway",
		"Render",
		"Fly.io",
		"DigitalOcean",
		"Heroku",
		"Docker",
		"Kubernetes",
		"GitHub Actions",
		"GitLab CI",
		"Jenkins",
		"Terraform",
		"Ansible",
	],
	Authentication: [
		"Auth0",
		"Firebase Auth",
		"Supabase Auth",
		"NextAuth.js",
		"Passport.js",
		"Clerk",
		"AWS Cognito",
		"Okta",
		"Magic Link",
		"JWT",
		"OAuth",
		"Better Auth",
	],
	"State Management": [
		"Redux",
		"Zustand",
		"Jotai",
		"Recoil",
		"MobX",
		"XState",
		"Context API",
		"Valtio",
		"TanStack Query",
		"SWR",
		"Apollo Client",
		"RTK Query",
	],
	Testing: [
		"Jest",
		"Vitest",
		"React Testing Library",
		"Cypress",
		"Playwright",
		"Selenium",
		"Mocha",
		"Chai",
		"Jasmine",
		"Enzyme",
		"Testing Library",
		"Puppeteer",
	],
	"Build Tools": [
		"Vite",
		"Webpack",
		"Rollup",
		"Parcel",
		"esbuild",
		"Turbopack",
		"SWC",
		"Babel",
		"ESLint",
		"Prettier",
		"Biome",
		"npm",
		"pnpm",
		"Yarn",
	],
	"Payment Processing": [
		"Stripe",
		"PayPal",
		"Square",
		"Braintree",
		"Razorpay",
		"Paddle",
		"Lemon Squeezy",
		"Chargebee",
		"Recurly",
		"Mollie",
	],
	"Analytics & Monitoring": [
		"Google Analytics",
		"Mixpanel",
		"Amplitude",
		"Segment",
		"PostHog",
		"Plausible",
		"Sentry",
		"LogRocket",
		"Datadog",
		"New Relic",
		"Grafana",
	],
	"CMS & Headless CMS": [
		"Contentful",
		"Sanity",
		"Strapi",
		"Prismic",
		"WordPress",
		"Ghost",
		"Payload CMS",
		"KeystoneJS",
		"Directus",
		"Hygraph",
	],
	"Real-time Communication": [
		"Socket.io",
		"WebSockets",
		"Pusher",
		"Ably",
		"Firebase Realtime",
		"Supabase Realtime",
		"WebRTC",
		"SignalR",
		"PubNub",
	],
};

export const FEATURE_CATEGORIES: Record<string, string[]> = {
	"Authentication & Authorization": [
		"User Registration",
		"Login/Logout",
		"Password Reset",
		"Social Login (OAuth)",
		"Two-Factor Authentication (2FA)",
		"Email Verification",
		"Role-Based Access Control (RBAC)",
		"Permission Management",
		"Session Management",
		"Multi-Factor Authentication",
		"Single Sign-On (SSO)",
		"Magic Link Authentication",
		"Biometric Authentication",
	],
	"User Management": [
		"User Profiles",
		"Profile Editing",
		"Avatar Upload",
		"User Settings",
		"Account Deletion",
		"User Search",
		"User Directory",
		"User Onboarding",
		"Activity Logs",
		"User Preferences",
	],
	"Data Management": [
		"CRUD Operations",
		"Data Import/Export",
		"File Upload",
		"Image Processing",
		"Data Validation",
		"Search & Filtering",
		"Pagination",
		"Sorting",
		"Bulk Operations",
		"Data Archiving",
		"Version Control",
		"Data Backup",
	],
	"Payment & Billing": [
		"Payment Processing",
		"Subscription Management",
		"Invoice Generation",
		"Payment History",
		"Refunds",
		"Multiple Payment Methods",
		"Billing Portal",
		"Tax Calculation",
		"Proration",
		"Coupon Management",
		"Trial Periods",
	],
	"Communication & Notifications": [
		"Email Notifications",
		"Push Notifications",
		"SMS Notifications",
		"In-App Messaging",
		"Chat System",
		"Comments & Replies",
		"Real-time Updates",
		"Notification Preferences",
		"Email Templates",
		"Message Queue",
	],
	"Analytics & Reporting": [
		"User Analytics",
		"Event Tracking",
		"Dashboard",
		"Reports",
		"Data Visualization",
		"Export Reports",
		"Custom Reports",
		"Real-time Analytics",
		"Funnel Analysis",
		"A/B Testing",
	],
	"Admin Features": [
		"Admin Dashboard",
		"User Management Panel",
		"Content Moderation",
		"System Settings",
		"Audit Logs",
		"Backup & Restore",
		"System Monitoring",
		"Feature Flags",
		"Impersonation",
		"Bulk Actions",
	],
	"Content Management": [
		"Rich Text Editor",
		"Media Library",
		"Categories & Tags",
		"Content Versioning",
		"Draft System",
		"Content Scheduling",
		"SEO Metadata",
		"Content Search",
		"Content Moderation",
	],
	"Integration & API": [
		"REST API",
		"GraphQL API",
		"Webhooks",
		"Third-party Services",
		"API Documentation",
		"API Rate Limiting",
		"API Authentication",
		"OAuth Integration",
		"Import from External Sources",
		"Export to External Services",
	],
	"Security & Compliance": [
		"Data Encryption",
		"GDPR Compliance",
		"Privacy Controls",
		"Audit Trails",
		"IP Whitelisting",
		"Rate Limiting",
		"CAPTCHA",
		"Content Security Policy",
		"Two-Factor Backup Codes",
	],
	"UI/UX Features": [
		"Multi-language Support (i18n)",
		"Dark Mode",
		"Responsive Design",
		"Accessibility (WCAG)",
		"Keyboard Shortcuts",
		"Drag & Drop",
		"Custom Themes",
		"Loading States",
		"Error Handling",
		"Offline Support",
	],
	"Social Features": [
		"User Following/Followers",
		"Social Sharing",
		"Likes & Reactions",
		"Comments System",
		"Activity Feed",
		"User Mentions",
		"Tagging Users",
		"Social Media Integration",
	],
	"E-commerce": [
		"Product Catalog",
		"Shopping Cart",
		"Checkout Process",
		"Order Management",
		"Inventory Management",
		"Product Reviews",
		"Wishlist",
		"Discount Codes",
		"Shipping Integration",
		"Product Recommendations",
	],
	"Performance & Optimization": [
		"Caching Strategy",
		"Image Optimization",
		"Lazy Loading",
		"Code Splitting",
		"CDN Integration",
		"Database Optimization",
		"Search Optimization",
		"Background Jobs",
	],
};
