/**
 * Evidence Text Component Generators
 *
 * Generates markdown and text-based components.
 */

/**
 * Generate a page header with title and optional subtitle
 */
export function generatePageHeader(config: {
	title: string;
	subtitle?: string;
	breadcrumb?: string[];
}): string {
	const parts: string[] = [];

	if (config.breadcrumb && config.breadcrumb.length > 0) {
		parts.push(config.breadcrumb.join(" > "));
		parts.push("");
	}

	parts.push(`# ${config.title}`);

	if (config.subtitle) {
		parts.push("");
		parts.push(`*${config.subtitle}*`);
	}

	return parts.join("\n");
}

/**
 * Generate a section header
 */
export function generateSectionHeader(
	title: string,
	level: 2 | 3 | 4 = 2,
): string {
	const hashes = "#".repeat(level);
	return `${hashes} ${title}`;
}

/**
 * Generate a horizontal divider with optional label
 */
export function generateDivider(label?: string): string {
	if (label) {
		return `---\n\n**${label}**\n`;
	}
	return "---";
}

/**
 * Generate a code block
 */
export function generateCodeBlock(
	code: string,
	language?: string,
	title?: string,
): string {
	const titleAttr = title ? ` title="${escapeAttr(title)}"` : "";
	const lang = language || "";

	return `\`\`\`${lang}${titleAttr}
${code}
\`\`\``;
}

/**
 * Generate a collapsible details section
 */
export function generateDetails(config: {
	summary: string;
	content: string;
	open?: boolean;
}): string {
	return `<Details title="${escapeAttr(config.summary)}" ${config.open ? "open" : ""}>

${config.content}

</Details>`;
}

/**
 * Generate a blockquote
 */
export function generateBlockquote(content: string, citation?: string): string {
	const lines = content.split("\n").map((line) => `> ${line}`);

	if (citation) {
		lines.push(`> — *${citation}*`);
	}

	return lines.join("\n");
}

/**
 * Generate a bullet list
 */
export function generateBulletList(items: string[], ordered?: boolean): string {
	return items
		.map((item, index) => (ordered ? `${index + 1}. ${item}` : `- ${item}`))
		.join("\n");
}

/**
 * Generate a metadata/info line
 */
export function generateMetadataLine(
	items: Array<{ label: string; value: string }>,
): string {
	return items.map((i) => `**${i.label}:** ${i.value}`).join(" · ");
}

/**
 * Generate LastRefreshed component
 */
export function generateLastRefreshed(): string {
	return "<LastRefreshed />";
}

/**
 * Generate a link
 */
export function generateLink(text: string, url: string): string {
	return `[${text}](${url})`;
}

/**
 * Generate an Alert/Note component
 */
export function generateAlert(config: {
	content: string;
	type?: "info" | "tip" | "warning" | "caution" | "note";
	title?: string;
}): string {
	const type = config.type || "note";

	if (config.title) {
		return `> [!${type}] ${config.title}
> ${config.content}`;
	}

	return `> [!${type}]
> ${config.content}`;
}

/**
 * Generate embedded SQL query (for Evidence's SQL blocks)
 */
export function generateSqlBlock(config: {
	name: string;
	query: string;
	description?: string;
}): string {
	const description = config.description
		? `<!-- ${config.description} -->\n`
		: "";

	return `${description}\`\`\`sql ${config.name}
${config.query}
\`\`\``;
}

/**
 * Generate a tabs container
 */
export function generateTabs(
	tabs: Array<{ id: string; label: string; content: string }>,
): string {
	const tabContents = tabs
		.map(
			(tab) => `<Tab id="${tab.id}" label="${escapeAttr(tab.label)}">

${tab.content}

</Tab>`,
		)
		.join("\n\n");

	return `<Tabs>

${tabContents}

</Tabs>`;
}

/**
 * Generate page footer
 */
export function generatePageFooter(config: {
	generatedAt?: Date;
	source?: string;
	version?: string;
}): string {
	const parts: string[] = ["---", ""];

	const metaItems: Array<{ label: string; value: string }> = [];

	if (config.generatedAt) {
		metaItems.push({
			label: "Generated",
			value: config.generatedAt.toISOString(),
		});
	}

	if (config.source) {
		metaItems.push({ label: "Source", value: config.source });
	}

	if (config.version) {
		metaItems.push({ label: "Version", value: config.version });
	}

	if (metaItems.length > 0) {
		parts.push(`*${generateMetadataLine(metaItems)}*`);
	}

	parts.push("");
	parts.push("*Generated by Fabric Reports*");

	return parts.join("\n");
}

/**
 * Escape attribute value
 */
function escapeAttr(str: string): string {
	return str
		.replace(/&/g, "&amp;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#39;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;");
}
